version: '2'
services:
  portainer:
    restart: always
    image: gcr.io/anyvision-training/portainer:latest
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - 9000:9000
volumes:
  portainer_data:
