apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: default
spec:
  dnsConfig:
    nameservers:
      - 1.2.3.4
    searches:
      - anyvision.local
  containers:
  - name: busybox
    image: busybox:1.28
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
