mongo: # mongo settings
  ip: mongodb
  port: 27017
  replicaSet: ''
api: # Api component (Dash-API) settings
  port: 3000
  ip: api
  protocol: http
bulkAmount: 5000    # bulk amount for each bulk operation on the collections
plugins: # Please add the plugin configuration for this array and the node process will run them, one each time
- apiPlugin:
    checkApiStatus: True # Plugin pre check if the api need to be down
    pluginPath: api # plugin folder path inside "plugins" folder
    databaseName: anyVision2 # database name to make migration on
    dumpFolderPath: /data/db_backups/
    limitVersion: '' # limit version for this migration if you want to migrate to the last one Please set to ''
    enable: True
- HQPlugin:
    checkApiStatus: False
    pluginPath: HQ
    databaseName: mapi
    dumpFolderPath: /data/db_backups/
    limitVersion: ''
    enable: False
