{
 "title": "Backend Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "COLLATE_NAME", "query": "label_values(name)" },
   { "name": "CAMERA_GROUP", "query": "label_values(camera_group)" },
   { "name": "MATCHES", "query": "label_values(matches)" }
  ]
 },
 "panels": [
  {
   "title": "handled tracks per minute",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(TrackProcessingStages{counter=\"finished_processing\", name=~\"$COLLATE_NAME\", matches=~\"$MATCHES\"}[1m])",
     "legendFormat": "tracks rate - {{`{{name}}`}}, matches: {{`{{matches}}`}}"
    },
    {
     "expr": "sum(increase(TrackProcessingStages{counter=\"finished_processing\", name=~\"$COLLATE_NAME\"}[1m]))",
     "legendFormat": "total tracks"
    }
   ]
  },
  {
   "title": "Backend Total Handling Elapsed Time",
   "type": "graph",
   "description": "Time elapsed from the first frame creation of a track until it sent to the API",
   "gridPos": { "h": 9, "w": 8, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, rate(BackendTotalHandlingElapsed_bucket{name=~\"$COLLATE_NAME\"}[1m]))",
     "legendFormat": "BackendTotalHandlingElapsed - {{`{{name}}`}} - percentile 50"
    },
    {
     "expr": "histogram_quantile(0.9, rate(BackendTotalHandlingElapsed_bucket{name=~\"$COLLATE_NAME\"}[1m]))",
     "legendFormat": "BackendTotalHandlingElapsed - {{`{{name}}`}} - percentile 90"
    },
    {
     "expr": "histogram_quantile(0.99, rate(BackendTotalHandlingElapsed_bucket{name=~\"$COLLATE_NAME\"}[1m]))",
     "legendFormat": "BackendTotalHandlingElapsed - {{`{{name}}`}} - percentile 99"
    }
   ]
  },
  {
   "title": "Failures",
   "type": "graph",
   "description": "Number of failed memsql insert queries when trying to insert track to TA",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "Failures{job=\"collate\", name=~\"$COLLATE_NAME\"}",
     "legendFormat": "{{`{{type}}`}}  - {{`{{name}}`}}"
    }
   ]
  },
  {
   "title": "Collate Timings",
   "type": "graph",
   "gridPos": { "h": 11, "w": 10, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, rate(TrackProcessingTime_bucket{name=~\"$COLLATE_NAME\", operation=~\"send_to_api\"}[1m]))",
     "legendFormat": "API report - {{`{{name}}`}} - percentile 50"
    },
    {
     "expr": "histogram_quantile(0.90, rate(TrackProcessingTime_bucket{name=~\"$COLLATE_NAME\", operation=~\"send_to_api\"}[1m]))",
     "legendFormat": "API report -{{`{{name}}`}}- percentile 90"
    },
    {
     "expr": "histogram_quantile(0.99, rate(TrackProcessingTime_bucket{name=~\"$COLLATE_NAME\", operation=~\"send_to_api\"}[1m]))",
     "legendFormat": "API report - {{`{{name}}`}} - percentile 99"
    },
    {
     "expr": "histogram_quantile(0.5, rate(TrackProcessingTime_bucket{name=~\"$COLLATE_NAME\", operation=~\"association\"}[1m]))",
     "legendFormat": "AssociationTime - {{`{{name}}`}} - percentile 50"
    },
    {
     "expr": "histogram_quantile(0.9, rate(TrackProcessingTime_bucket{name=~\"$COLLATE_NAME\", operation=~\"association\"}[1m]))",
     "legendFormat": "AssociationTime - {{`{{name}}`}} - percentile 90"
    },
    {
     "expr": "histogram_quantile(0.99, rate(TrackProcessingTime_bucket{name=~\"$COLLATE_NAME\", operation=~\"association\"}[1m]))",
     "legendFormat": "AssociationTime - {{`{{name}}`}} - percentile 99"
    },
    {
     "expr": "histogram_quantile(0.5, rate(ArchiveTime_bucket{name=~\"$COLLATE_NAME\"}[1m]))",
     "legendFormat": "ArchiveTime - {{`{{name}}`}} - percentile 50"
    },
    {
     "expr": "histogram_quantile(0.90, rate(ArchiveTime_bucket{name=~\"$COLLATE_NAME\"}[1m]))",
     "legendFormat": "ArchiveTime - {{`{{name}}`}} - percentile 90"
    },
    {
     "expr": "histogram_quantile(0.99, rate(ArchiveTime_bucket{name=~\"$COLLATE_NAME\"}[1m]))",
     "legendFormat": "ArchiveTime - {{`{{name}}`}} - percentile 99"
    },
    {
     "expr": "histogram_quantile(0.5, rate(TrackProcessingTime_bucket{name=~\"$COLLATE_NAME\", operation=~\"reid\"}[1m]))",
     "legendFormat": "ReidTime - {{`{{name}}`}} - percentile 50"
    },
    {
     "expr": "histogram_quantile(0.9, rate(TrackProcessingTime_bucket{name=~\"$COLLATE_NAME\", operation=~\"reid\"}[1m]))",
     "legendFormat": "ReidTime - {{`{{name}}`}} - percentile 90"
    },
    {
     "expr": "histogram_quantile(0.99, rate(TrackProcessingTime_bucket{name=~\"$COLLATE_NAME\", operation=~\"reid\"}[1m]))",
     "legendFormat": "ReidTime - {{`{{name}}`}} - percentile 99"
    },
    {
     "expr": "histogram_quantile(0.5, rate(TrackProcessingTime_bucket{name=~\"$COLLATE_NAME\", operation=\"queue\"}[1m]))",
     "legendFormat": "queue - {{`{{name}}`}} - percentile 50"
    },
    {
     "expr": "histogram_quantile(0.9, rate(TrackProcessingTime_bucket{name=~\"$COLLATE_NAME\", operation=\"queue\"}[1m]))",
     "legendFormat": "queue - {{`{{name}}`}} - percentile 90"
    },
    {
     "expr": "histogram_quantile(0.99, rate(TrackProcessingTime_bucket{name=\"$COLLATE_NAME\", operation=\"queue\"}[1m]))",
     "legendFormat": "queue - {{`{{name}}`}} - percentile 99"
    },
    {
     "expr": "sum(histogram_quantile(0.5, rate(TrackProcessingTime_bucket{name=~\"$COLLATE_NAME\"}[1m])))",
     "legendFormat": "total - {{`{{name}}`}} - percentile 50"
    },
    {
     "expr": "sum(histogram_quantile(0.9, rate(TrackProcessingTime_bucket{name=~\"$COLLATE_NAME\"}[1m])))",
     "legendFormat": "total - {{`{{name}}`}} - percentile 90"
    },
    {
     "expr": "sum(histogram_quantile(0.99, rate(TrackProcessingTime_bucket{name=~\"$COLLATE_NAME\"}[1m])))",
     "legendFormat": "total - {{`{{name}}`}} - percentile 99"
    }
   ]
  },
  {
   "title": "Collate Queue Size",
   "type": "graph",
   "description": "Queue size of pending tracks at the Collate service",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "CollateQsize{name=~\"$COLLATE_NAME\"}",
     "legendFormat": "CollateQsize - {{`{{name}}`}}"
    },
    {
     "expr": "histogram_quantile(0.5, rate(CollatePending_bucket{name=~\"$COLLATE_NAME\"}[1m]))",
     "legendFormat": "collate -  {{`{{name}}`}}- pending 50"
    },
    {
     "expr": "histogram_quantile(0.90, rate(CollatePending_bucket{name=~\"$COLLATE_NAME\"}[1m]))",
     "legendFormat": "collate - {{`{{name}}`}} - pending 90"
    },
    {
     "expr": "histogram_quantile(0.99, rate(CollatePending_bucket{name=~\"$COLLATE_NAME\"}[1m]))",
     "legendFormat": "collate - {{`{{name}}`}} - pending 99"
    }
   ]
  },
  {
   "title": "Track Archive Queue Size",
   "type": "graph",
   "description": "Queue size of pending tracks at the Track-Archive service",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "TrackArchiveQSize{name=~\"$COLLATE_NAME\"}",
     "legendFormat": "TrackArchiveQSize - {{`{{name}}`}}"
    }
   ]
  },
  {
   "title": "Track Archive Batch Size",
   "type": "graph",
   "description": "Size of batch of tracks sent to Track-Archive service",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "TrackArchiveBatchSize{name=~\"$COLLATE_NAME\"}",
     "legendFormat": "TrackArchiveBatchSize - {{`{{name}}`}}"
    }
   ]
  },
  {
   "title": "Track Processing Stages",
   "type": "graph",
   "description": "Number of tracks:\n* received from zmq\n* pulled from collate_queue\n* finished processed\nat the Collate service",
   "gridPos": { "h": 17, "w": 10, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "idelta(TrackProcessingStages{counter=\"received_from_zmq\",name=~\"$COLLATE_NAME\"}[1m])",
     "legendFormat": "TrackProcessingStages (received_from_zmq) - {{`{{name}}`}}"
    },
    {
     "expr": "idelta(TrackProcessingStages{counter=\"pulled_from_collate_queue\",name=~\"$COLLATE_NAME\"}[1m])",
     "legendFormat": "TrackProcessingStages (pulled_from_collate_queue) - {{`{{name}}`}}"
    },
    {
     "expr": "idelta(TrackProcessingStages{counter=\"finished_processing\",name=~\"$COLLATE_NAME\"}[1m])",
     "legendFormat": "TrackProcessingStages (finished_processing) - {{`{{name}}`}}"
    }
   ]
  },
  {
   "title": "Association Managers Size",
   "type": "graph",
   "description": "AssociationManagers size of camera group at the Collate service",
   "gridPos": { "h": 5, "w": 14, "x": 10, "y": 25 },
   "repeat": "camera",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(AssociationManagersSize{name=~\"$COLLATE_NAME\"})",
     "legendFormat": "AssociationManagersSize - {{`{{name}}`}}"
    }
   ]
  },
  {
   "title": "handled tracks/sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(TrackProcessingStages{counter=\"finished_processing\"}[1m])/60"
    }
   ]
  }
 ]
}