{
 "title": "API Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "CAMERA_ID", "query": "label_values(cameraId)" },
   { "name": "CAMERA_NAME", "query": "label_values(cameraName)" },
   { "name": "EDGE", "query": "label_values(edge)" },
   { "name": "PIPE_ID", "query": "label_values(pipeId)" },
   { "name": "CAMERA_TYPE", "query": "label_values(cameraType)" }
  ]
 },
 "panels": [
  {
   "title": "Cameras total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "camera_on", "legendFormat": "Cameras ON" },
    { "expr": "camera_failed", "legendFormat": "Cameras failed" },
    { "expr": "camera_total", "legendFormat": "Camera total" }
   ]
  },
  {
   "title": "Total Ignores",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "ignore_counter", "legendFormat": "Ignores" }
   ]
  },
  {
   "title": "Suspects In REID Count ",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(ReidSuspectsCount)", "legendFormat": "Suspects " },
    { "expr": "sum(ReidFeaturesCount)", "legendFormat": "Features " }
   ]
  },
  {
   "title": "Total tracks average delta time from first frame to dashboard (Per minute)",
   "type": "graph",
   "description": "Detection delta time between FIRST frame of track in pipe to api (mongo)",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(detection_delta_from_start_track_sum[1m]))/sum(rate(detection_delta_from_start_track_count[1m]))",
     "legendFormat": "Average Delta Time"
    }
   ]
  },
  {
   "title": "Tracks avg  processing time (Per minute)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "s", "label": "seconds" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_route_new_detection_time_sum[1m]))/sum(rate(http_route_new_detection_time_count[1m]))",
     "legendFormat": "Average Delta Time"
    }
   ]
  },
  {
   "title": "Track average delta time from last frame to dashboard (Per minute)",
   "type": "graph",
   "description": "Detection delta time between LAST frame of track in pipe to api (mongo)",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(detection_delta_from_end_track_sum[1m]))/sum(rate(detection_delta_from_end_track_count[1m]))",
     "legendFormat": "Average Delta Time"
    }
   ]
  },
  {
   "title": "Track average delta time from first frame to Dashboard - By Quantile",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(histogram_quantile(0.99, rate(detection_delta_from_start_track_bucket[1m])))",
     "legendFormat": "Avg Delta Time of Quantile 99%"
    },
    {
     "expr": "avg(histogram_quantile(0.90, rate(detection_delta_from_start_track_bucket[1m])))",
     "legendFormat": "Avg Delta Time of Quantile 90%"
    },
    {
     "expr": "avg(histogram_quantile(0.5, rate(detection_delta_from_start_track_bucket[1m])))",
     "legendFormat": "Avg Delta Time of Quantile 50%"
    }
   ]
  },
  {
   "title": "Top 10 delayed camera (Only in Api)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "s", "label": "seconds" }
   ],
   "targets": [
    {
     "expr": "topk(10, avg by (cameraId) (rate(http_route_new_detection_time_bucket{cameraId=~\"$CAMERA_ID\"}[1m])))",
     "legendFormat": "Camera ID - {{`{{ cameraId }}`}}"
    }
   ]
  },
  {
   "title": "Track average delta time from last frame to Dashboard - By Quantile",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(histogram_quantile(0.99, rate(detection_delta_from_end_track_bucket[1m])))",
     "legendFormat": "Avg Delta Time of Quantile 99%"
    },
    {
     "expr": "avg(histogram_quantile(0.9, rate(detection_delta_from_end_track_bucket[1m])))",
     "legendFormat": "Avg Delta Time of Quantile 90%"
    },
    {
     "expr": "avg(histogram_quantile(0.5, rate(detection_delta_from_end_track_bucket[1m])))",
     "legendFormat": "Avg Delta Time of Quantile 50%"
    }
   ]
  },
  {
   "title": "Tracks in API",
   "type": "graph",
   "description": "NOTICE - Total detections and recognitions can be filtered by camera id, pipe id and edge.\nFailed detctions can be filtered by camera id or camera type only.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(new_detection_count{cameraId=~\"$CAMERA_ID\", edge=~\"$EDGE\", pipeId=~\"$PIPE_ID\"})",
     "legendFormat": "Total detections"
    },
    {
     "expr": "sum(new_detection_count{isSubject=\"true\", cameraId=~\"$CAMERA_ID\", edge=~\"$EDGE\", pipeId=~\"$PIPE_ID\"})",
     "legendFormat": "Total Recognitions"
    },
    {
     "expr": "sum(failed_detection_count{cameraId=~\"$CAMERA_ID\", cameraType=~\"$CAMERA_TYPE\"})",
     "legendFormat": "Total Tracks Failed"
    }
   ]
  },
  {
   "title": "Track average delta time from first frame to Dashboard (Quantile 99%) - By Cameras",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg by (cameraName) (histogram_quantile(0.99,rate(detection_delta_from_start_track_bucket[1m])))",
     "legendFormat": "Delta of  {{`{{ cameraName }}`}}  99%"
    }
   ]
  },
  {
   "title": "Track average delta time from last frame to Dashboard (Quantile 99%) - By Cameras",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 28 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg by (cameraName) (histogram_quantile(0.99,rate(detection_delta_from_end_track_bucket[1m])))",
     "legendFormat": "Delta of  {{`{{ cameraName }}`}}   99%"
    }
   ]
  },
  {
   "title": "Total tracks in API By cameras",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (cameraName)(new_detection_count{edge=~\"$EDGE\", pipeId=~\"$PIPE_ID\"})",
     "legendFormat": "Total detections from  '{{`{{ cameraName }}`}}'"
    },
    {
     "expr": "sum by (cameraName)(new_detection_count{isSubject=\"true\", edge=~\"$EDGE\", pipeId=~\"$PIPE_ID\"})",
     "legendFormat": "Total Recognitions from ' {{`{{ cameraName }}`}}'"
    },
    {
     "expr": "sum by (cameraName)(failed_detection_count{cameraType=~\"$CAMERA_TYPE\"})",
     "legendFormat": "Total Tracks Failed from ' {{`{{ cameraName }}`}}'"
    }
   ]
  },
  {
   "title": "Track average delta time from first frame to Dashboard (Quantile 90%) - By Cameras",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg by (cameraName) (histogram_quantile(0.9,rate(detection_delta_from_start_track_bucket[1m])))",
     "legendFormat": "Delta of  {{`{{ cameraName }}`}}  90%"
    }
   ]
  },
  {
   "title": "Track average delta time from last frame to Dashboard (Quantile 90%) - By Cameras",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 38 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg by (cameraName) (histogram_quantile(0.9,rate(detection_delta_from_end_track_bucket[1m])))",
     "legendFormat": "Delta of  {{`{{ cameraName }}`}}   90%"
    }
   ]
  },
  {
   "title": "Track average delta time from first frame to Dashboard (Quantile 50%) - By Cameras",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg by (cameraName) (histogram_quantile(0.5,rate(detection_delta_from_start_track_bucket[1m])))",
     "legendFormat": "Delta of  {{`{{ cameraName }}`}}   50%"
    }
   ]
  },
  {
   "title": "Track average delta time from last frame to Dashboard (Quantile 50%) - By Cameras",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 46 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg by (cameraName) (histogram_quantile(0.5,rate(detection_delta_from_end_track_bucket[1m])))",
     "legendFormat": "Delta of  {{`{{ cameraName }}`}}   50%"
    }
   ]
  }
 ]
}