{
 "title": "Pipeline Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "HOST", "query": "label_values(host)" },
   { "name": "PIPE_ID", "query": "label_values(pipe)" },
   { "name": "GPU", "query": "label_values(gpu)" },
   { "name": "CAMERA_GROUP", "query": "label_values(group)" },
   { "name": "CAMERA", "query": "label_values(cameraId)" },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "abs(MemoryUsageCPU{process=~\"Feature Extraction service\", cameraId=~\"$CAMERA\",host=~\"$HOST\",gpu=~\"$GPU\",pipe=~\"$PIPE_ID\",group=~\"$CAMERA_GROUP\"})",
     "legendFormat": "Feature Extraction - {{`{{cameraId}}`}}"
    },
    {
     "expr": "abs(MemoryUsageCPU{process=~\"Object Detection service\", cameraId=~\"$CAMERA\",host=~\"$HOST\",gpu=~\"$GPU\",pipe=~\"$PIPE_ID\",group=~\"$CAMERA_GROUP\"})",
     "legendFormat": "Object Detection - {{`{{cameraId}}`}}"
    },
    {
     "expr": "abs(MemoryUsageCPU{process=~\"Feature Extraction service\", cameraId=~\"$CAMERA\",host=~\"$HOST\",gpu=~\"$GPU\",pipe=~\"$PIPE_ID\",group=~\"$CAMERA_GROUP\"})",
     "legendFormat": "Feature Extraction - {{`{{cameraId}}`}}"
    },
    {
     "expr": "abs(MemoryUsageCPU{process=~\"Tracking service\", cameraId=~\"$CAMERA\",host=~\"$HOST\",gpu=~\"$GPU\",pipe=~\"$PIPE_ID\",group=~\"$CAMERA_GROUP\"})",
     "legendFormat": "Tracking - {{`{{cameraId}}`}}"
    },
    {
     "expr": "abs(MemoryUsageCPU{process=~\"Frame Store Watcher process\", cameraId=~\"$CAMERA\",host=~\"$HOST\",gpu=~\"$GPU\",pipe=~\"$PIPE_ID\",group=~\"$CAMERA_GROUP\"})",
     "legendFormat": "Frame Store Watcher - {{`{{cameraId}}`}}"
    }
   ]
  },
  {
   "title": "Faces/minute",
   "type": "graph",
   "description": "Amount of detected faces/minute",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(FeatureExtractionFacesCounter_total{cameraId=~\"$CAMERA\",host=~\"$HOST\",gpu=~\"$GPU\",pipe=~\"$PIPE_ID\",group=~\"$CAMERA_GROUP\"}[1m]))",
     "legendFormat": "Total Features"
    }
   ]
  },
  {
   "title": "Tracks/minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(TrackingServiceTracksCount_total{cameraId=~\"$CAMERA\",host=~\"$HOST\",pipe=~\"$PIPE_ID\",group=~\"$CAMERA_GROUP\"}[1m]))",
     "legendFormat": "Total Tracks Number"
    },
    {
     "expr": "increase(TrackingServiceTracksCount_total{cameraId=~\"$CAMERA\",host=~\"$HOST\",pipe=~\"$PIPE_ID\",group=~\"$CAMERA_GROUP\"}[1m])",
     "legendFormat": "Tracks - {{`{{cameraId}}`}}"
    }
   ]
  },
  {
   "title": "Frames Count/minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(ObjectDetectorFacesPerFrame_count{cameraId=~\"$CAMERA\",host=~\"$HOST\",gpu=~\"$GPU\",pipe=~\"$PIPE_ID\",group=~\"$CAMERA_GROUP\"}[1m]))",
     "legendFormat": "Object Detection Frames"
    },
    {
     "expr": "sum(increase(FeatureExtractionFramesCounter_total{cameraId=~\"$CAMERA\",host=~\"$HOST\",gpu=~\"$GPU\",pipe=~\"$PIPE_ID\",group=~\"$CAMERA_GROUP\"}[1m]))",
     "legendFormat": "Feature Extraction Frames"
    }
   ]
  },
  {
   "title": "Top 10 delayed cameras",
   "type": "graph",
   "description": "Delay time in seconds between FrameStoreDemux to Object Detection",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(10, ObjectDetectionDelayTime{cameraId=~\"$CAMERA\",host=~\"$HOST\",gpu=~\"$GPU\",pipe=~\"$PIPE_ID\",group=~\"$CAMERA_GROUP\"})",
     "legendFormat": "{{`{{host}}`}} - camera {{`{{cameraId}}`}} - gpu {{`{{gpu}}`}}"
    }
   ]
  },
  {
   "title": "Feature Extraction Delay Time",
   "type": "graph",
   "description": "Latency in seconds of detections received from Object Detection service to Feature Extraction service",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(10, histogram_quantile(0.99, rate(FeatureExtractionLatencyCounter_bucket{cameraId=~\"$CAMERA\",host=~\"$HOST\",gpu=~\"$GPU\",pipe=~\"$PIPE_ID\",group=~\"$CAMERA_GROUP\"}[1m])))",
     "legendFormat": "Delay Time - {{`{{cameraId}}`}}"
    }
   ]
  },
  {
   "title": "Track Duration (seconds)",
   "type": "graph",
   "description": "Time in seconds from when track was created till it is terminated",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(TrackingTime_bucket{cameraId=~\"$CAMERA\",host=~\"$HOST\",pipe=~\"$PIPE_ID\",group=~\"$CAMERA_GROUP\"}[1m]))",
     "legendFormat": "Track Duration - 0.99 - {{`{{cameraId}}`}}"
    },
    {
     "expr": "histogram_quantile(0.9, rate(TrackingTime_bucket{cameraId=~\"$CAMERA\",host=~\"$HOST\",pipe=~\"$PIPE_ID\",group=~\"$CAMERA_GROUP\"}[1m]))",
     "legendFormat": "Track Duration - 0.9 - {{`{{cameraId}}`}}"
    },
    {
     "expr": "histogram_quantile(0.5, rate(TrackingTime_bucket{cameraId=~\"$CAMERA\",host=~\"$HOST\",pipe=~\"$PIPE_ID\",group=~\"$CAMERA_GROUP\"}[1m]))",
     "legendFormat": "Track Duration - 0.5 - {{`{{cameraId}}`}}"
    }
   ]
  },
  {
   "title": "Tracks Length (Frames)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(TrackingTrackLength_bucket{cameraId=~\"$CAMERA\",host=~\"$HOST\",pipe=~\"$PIPE_ID\",group=~\"$CAMERA_GROUP\"}[1m]))",
     "legendFormat": "Tracks Length 0.99 - {{`{{cameraId}}`}}"
    },
    {
     "expr": "histogram_quantile(0.5, rate(TrackingTrackLength_bucket{cameraId=~\"$CAMERA\",host=~\"$HOST\",pipe=~\"$PIPE_ID\",group=~\"$CAMERA_GROUP\"}[1m]))",
     "legendFormat": "Tracks Length 0.5 - {{`{{cameraId}}`}}"
    },
    {
     "expr": "histogram_quantile(0.9, rate(TrackingTrackLength_bucket{cameraId=~\"$CAMERA\",host=~\"$HOST\",pipe=~\"$PIPE_ID\",group=~\"$CAMERA_GROUP\"}[1m]))",
     "legendFormat": "Tracks Length 0.9 - {{`{{cameraId}}`}}"
    }
   ]
  },
  {
   "title": "TOP S3 store times/sec",
   "type": "graph",
   "description": "Time in seconds took to store tracks at Objects Storage",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(10, histogram_quantile(0.99, rate(TrackingServiceStoringTime_bucket{cameraId=~\"$CAMERA\",host=~\"$HOST\",pipe=~\"$PIPE_ID\",group=~\"$CAMERA_GROUP\"}[1m])))",
     "legendFormat": "{{`{{host}}`}} - camera {{`{{cameraId}}`}}"
    }
   ]
  },
  {
   "title": "Pipeline Failures",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(ObjectDetectionDecodingFailuresCounter_total{cameraId=~\"$CAMERA\",host=~\"$HOST\",gpu=~\"$GPU\",pipe=~\"$PIPE_ID\",group=~\"$CAMERA_GROUP\"}[1m])",
     "legendFormat": "Decoding Failures - {{`{{cameraId}}`}}"
    },
    {
     "expr": "sum(increase(TrackingServiceFailuresCount_total{cameraId=~\"$CAMERA\",host=~\"$HOST\",pipe=~\"$PIPE_ID\",group=~\"$CAMERA_GROUP\",component=~\"s3\"}[1m]))",
     "legendFormat": "S3 Failures - {{`{{cameraId}}`}}"
    },
    {
     "expr": "sum(increase(TrackingServiceFailuresCount_total{cameraId=~\"$CAMERA\",host=~\"$HOST\",pipe=~\"$PIPE_ID\",group=~\"$CAMERA_GROUP\",component=~\"zmq\"}[1m]))",
     "legendFormat": "Collate Failures - {{`{{cameraId}}`}}"
    }
   ]
  },
  {
   "title": "ReidSuspectsCount",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(ReidSuspectsCount)" },
    { "expr": "sum(ReidFeaturesCount)" }
   ]
  },
  {
   "title": "Effective FPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bottomk(10, ObjectDetectorFrameSkipping{cameraId=~\"$CAMERA\",host=~\"$HOST\",gpu=~\"$GPU\",pipe=~\"$PIPE_ID\",group=~\"$CAMERA_GROUP\"} * (StreamFPS{cameraId=~\"$CAMERA\",host=~\"$HOST\",gpu=~\"$GPU\",pipe=~\"$PIPE_ID\",group=~\"$CAMERA_GROUP\"}/10))",
     "legendFormat": "{{`{{host}}`}} camera {{`{{cameraId}}`}} gpu {{`{{gpu}}`}}"
    }
   ]
  },
  {
   "title": "Frame Processing latency  percentile 99",
   "type": "graph",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(10, histogram_quantile(0.99, rate(FrameProcessLatency_bucket{cameraId=~\"$CAMERA\",host=~\"$HOST\",gpu=~\"$GPU\",pipe=~\"$PIPE_ID\",group=~\"$CAMERA_GROUP\"}[1m]))) ",
     "legendFormat": "{{`{{host}}`}} camera {{`{{cameraId}}`}} gpu {{`{{gpu}}`}}"
    }
   ]
  },
  {
   "title": "Frame Processing Latency Avg",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 11, "y": 32 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(10, rate(FrameProcessLatency_sum{cameraId=~\"$CAMERA\",host=~\"$HOST\",gpu=~\"$GPU\",pipe=~\"$PIPE_ID\",group=~\"$CAMERA_GROUP\"}[1m]) / rate(FrameProcessLatency_count{cameraId=~\"$CAMERA\",host=~\"$HOST\",gpu=~\"$GPU\",pipe=~\"$PIPE_ID\",group=~\"$CAMERA_GROUP\"}[1m]))",
     "legendFormat": "{{`{{host}}`}} camera {{`{{cameraId}}`}} gpu {{`{{gpu}}`}}"
    },
    {
     "expr": "rate(ObjectDetectionLatency_sum{cameraId=~\"$CAMERA\",host=~\"$HOST\",gpu=~\"$GPU\",pipe=~\"$PIPE_ID\",group=~\"$CAMERA_GROUP\"}[1m]) / rate(ObjectDetectionLatency_count{cameraId=~\"$CAMERA\",host=~\"$HOST\",gpu=~\"$GPU\",pipe=~\"$PIPE_ID\",group=~\"$CAMERA_GROUP\"}[1m]) + rate(FrameProcessLatency_sum{cameraId=~\"$CAMERA\",host=~\"$HOST\",gpu=~\"$GPU\",pipe=~\"$PIPE_ID\",group=~\"$CAMERA_GROUP\"}[1m]) / rate(FrameProcessLatency_count{cameraId=~\"$CAMERA\",host=~\"$HOST\",gpu=~\"$GPU\",pipe=~\"$PIPE_ID\",group=~\"$CAMERA_GROUP\"}[1m])",
     "legendFormat": "{{`{{host}}`}} camera {{`{{cameraId}}`}} gpu {{`{{gpu}}`}}"
    }
   ]
  },
  {
   "title": "Detector Latency percentile 99",
   "type": "graph",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(10, histogram_quantile(0.99, rate(ObjectDetectionLatency_bucket{cameraId=~\"$CAMERA\",host=~\"$HOST\",gpu=~\"$GPU\",pipe=~\"$PIPE_ID\",group=~\"$CAMERA_GROUP\"}[1m]))) ",
     "legendFormat": "{{`{{host}}`}} camera {{`{{cameraId}}`}} gpu {{`{{gpu}}`}}"
    }
   ]
  },
  {
   "title": "Detector Latency average",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 11, "y": 42 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(10, rate(ObjectDetectionLatency_sum{cameraId=~\"$CAMERA\",host=~\"$HOST\",gpu=~\"$GPU\",pipe=~\"$PIPE_ID\",group=~\"$CAMERA_GROUP\"}[1m]) / rate(ObjectDetectionLatency_count{cameraId=~\"$CAMERA\",host=~\"$HOST\",gpu=~\"$GPU\",pipe=~\"$PIPE_ID\",group=~\"$CAMERA_GROUP\"}[1m]))",
     "legendFormat": "{{`{{host}}`}} camera {{`{{cameraId}}`}} gpu {{`{{gpu}}`}}"
    }
   ]
  },
  {
   "title": "Decoder Latency percentile 99",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(10, histogram_quantile(0.99, rate(DecoderLatency_bucket{cameraId=~\"$CAMERA\",host=~\"$HOST\",gpu=~\"$GPU\",pipe=~\"$PIPE_ID\",group=~\"$CAMERA_GROUP\"}[1m]))) ",
     "legendFormat": "{{`{{host}}`}} camera {{`{{cameraId}}`}} gpu {{`{{gpu}}`}}"
    }
   ]
  },
  {
   "title": "Decoder Latency Avg",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 52 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(10, rate(DecoderLatency_sum{cameraId=~\"$CAMERA\",host=~\"$HOST\",gpu=~\"$GPU\",pipe=~\"$PIPE_ID\",group=~\"$CAMERA_GROUP\"}[1m]) / rate(DecoderLatency_count{cameraId=~\"$CAMERA\",host=~\"$HOST\",gpu=~\"$GPU\",pipe=~\"$PIPE_ID\",group=~\"$CAMERA_GROUP\"}[1m]))",
     "legendFormat": "{{`{{host}}`}} camera {{`{{cameraId}}`}} gpu {{`{{gpu}}`}}"
    }
   ]
  },
  {
   "title": "Faces/Frame ",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "histogram_quantile(1, rate(ObjectDetectorFacesPerFrame_bucket{cameraId=~\"$CAMERA\",host=~\"$HOST\",gpu=~\"$GPU\",pipe=~\"$PIPE_ID\",group=~\"$CAMERA_GROUP\"}[1m]))"
    }
   ]
  },
  {
   "title": "Cameras Info",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 68 },
   "targets": [
    {
     "expr": "ObjectDetectorCameraInfo_info{cameraId=~\"$CAMERA\",host=~\"$HOST\",gpu=~\"$GPU\",pipe=~\"$PIPE_ID\",group=~\"$CAMERA_GROUP\"}"
    }
   ]
  }
 ]
}