#filename: docker-compose-migration-db.yml
version: '3.3'


networks:
  prod:

services:

  mongodb:
    image: gcr.io/anyvision-training/mongo:3.6-jessie
    restart: always
    networks:
      prod:
        aliases:
          - mongodb.tls.ai
    #ports:
      #- "27017:27017"
    volumes:
      - /ssd/mongo_db_data:/data/db
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - env/global.env
    logging:
      options:
        max-size: 1g



  migration_manager:
    image: gcr.io/anyvision-training/migration_manager:development
    #restart: always
    networks:
      prod:
        aliases:
          - migration-manager.tls.ai
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /storage/migration_db_data:/var/tmp
      - /ssd/mongo_db_backups:/data/db_backups
    depends_on:
      - mongodb
    environment:
      - MONGO_DB_IP=mongodb.tls.ai
      - MONGO_DB_NAME=anyVision2
      - MONGO_DB_PORT=27017
      - API_IP=api.tls.ai
      - API_PORT=3000
      - API_PROTOCOL=http
      - RUN_AS_USER=user
      - ENABLE_MIGRATION_MANAGER=true
      - MONGO_DB_DUMP_PATH=/data/db_backups/
      - MONGO_DB_RESTORE_PATH=/data/db_backups/
      - BULK_AMOUNT=5000
      #- LIMIT_VERSION=
      #- ENABLE_CHOWN=true
    env_file:
      - env/global.env
    logging:
      options:
        max-size: 1g
