version: '3.3'

volumes:
  backend_data:

networks:
  anyvision:
#    driver: bridge
#    ipam:
#      driver: default
#      config:
#        - subnet: 172.14.0.0/16
#          gateway: 172.14.0.1

services:

  dslr:
    restart: always
    privileged: true
    networks:
      - anyvision
    image: gcr.io/anyvision-training/dslr
    volumes:
      - type: volume
        source: backend_data
        target: /root/pipe_data
      - type: bind
        source: c:/anv/storage
        target: /var/www/html
      - type: bind
        source: c:/anv/storage/logs
        target: /var/www/html/logs
      - type: bind
        source: c:/anv/storage/cameraMount
        target: /root/mount
    environment:
      - pipe_cpu_mode=true
    env_file:
      - env/dslr.env
      - env/backend.env
      - env/global.env
