#filename: docker-compose-facekey.yml
version: '3.3'


networks:
  prod:

services:


  face-key-fe:
    image: gcr.io/anyvision-training/face-key-fe:latest
    restart: always
    networks:
      prod:
        aliases:
          - face-key-fe.tls.ai
    ports:
      - "3002:3002"
    volumes:
      - /usr/local/share/ca-certificates:/usr/local/share/ca-certificates
      - /etc/localtime:/etc/localtime:ro
      #- /etc/timezone:/etc/timezone:ro
    environment:
      - face-key-be_ip=face-key-be.tls.ai
      #- face-key-be_username=admin
      #- face-key-be_password=admin
    env_file:
      - env/global.env
    logging:
      options:
        max-size: 1g



  face-key-be:
    image: gcr.io/anyvision-training/face-key-be:latest
    restart: always
    networks:
      prod:
        aliases:
          - face-key-be.tls.ai
    volumes:
      - /storage:/var/www/html
      - /usr/local/share/ca-certificates:/usr/local/share/ca-certificates
      - /etc/localtime:/etc/localtime:ro
      #- /etc/timezone:/etc/timezone:ro
    env_file:
      - env/global.env
    logging:
      options:
        max-size: 1g