#filename: docker-compose-apimaster.yml
version: '3.3'

# volumes:
#   consul_data:
#   consul_agent_data:


networks:
  prod:
    ipam:
      driver: default
      config:
      -
        subnet: 172.30.30.0/24

services:


  dashboard-master:
    image: gcr.io/anyvision-production/dashboard-master:1.1.0-rc.14
    restart: always
    networks:
      prod:
        aliases:
          - dashboard-master.tls.ai
    ports:
      #- "443:443"
      - "80:80"
    volumes:
      - /usr/local/share/ca-certificates:/usr/local/share/ca-certificates
      - /etc/localtime:/etc/localtime:ro
      #- /etc/timezone:/etc/timezone:ro
    environment:
      - limit_rate_speed=0
      - master_api_ip=api-master.tls.ai
      - master_api_port=2000
      - master_api_username=admin
      - master_api_password=admin
    env_file:
      - env/global.env
    logging:
      options:
        max-size: 1g




  api-master:
    image: gcr.io/anyvision-production/api-master:1.1.0-rc.17
    restart: always
    networks:
      prod:
        aliases:
          - api-master.tls.ai
    ports:
      - "2000:2000"
      - "38383:38383"
    volumes:
      - /storage:/var/www/html
      - /usr/local/share/ca-certificates:/usr/local/share/ca-certificates
      - /etc/localtime:/etc/localtime:ro
      - /ssd/apimaster/keys:/usr/local/share/keys
    environment:
      - API_MASTER_PORT=2000
      - SELF_API_HOST=api.tls.ai
      - SELF_API_PORT=3000
      - MONGO_DB_IP=mongodb.tls.ai
      - RMQ_EXCHANGE_HOST=rabbitmq.tls.ai
      - RMQ_EXCHANGE_PORT=5672      
      - MONGO_DB_PORT=27017
      - RUN_AS_USER=user
      - API_MASTER_IP=api-master.tls.ai
      #- ENABLE_CHOWN=false
    env_file:
      - env/global.env
      - env/api-master.env
    logging:
      options:
        max-size: 1g

