#filename: docker-compose-apimaster.yml
version: '3.3'


networks:
  anyvision:


services:


  dashboard-master:
    image: gcr.io/anyvision-production/dashboard-master:1.20.1-rc.2
    restart: always
    networks:
      anyvision:
        aliases:
          - dashboard-master-${node_name:-localnode}.tls.ai
    ports:
      #- "443:443"
      - "80:80"
    volumes:
      - /usr/local/share/ca-certificates:/usr/local/share/ca-certificates
      - /etc/localtime:/etc/localtime:ro
      #- /etc/timezone:/etc/timezone:ro
    environment:
      - limit_rate_speed=0
      - master_api_ip=api-master.tls.ai
      - master_api_username=admin
      - master_api_password=admin
    env_file:
      - env/global.env
    logging:
      options:
        max-size: 1g



  api-master:
    image: gcr.io/anyvision-production/api-master:1.20.1-rc.2
    restart: always
    networks:
      anyvision:
        aliases:
          - api-master.tls.ai
    ports:
      - "27183:27183"
    volumes:
      - /storage:/var/www/html
      - /usr/local/share/ca-certificates:/usr/local/share/ca-certificates
      - /etc/localtime:/etc/localtime:ro
      #- /etc/timezone:/etc/timezone:ro
    environment:
      - API_MASTER_PORT=27183
      - SELF_API_HOST=api.tls.ai
      - SELF_API_PORT=3000
      - MONGO_DB_IP=mongodb.tls.ai
      - MONGO_DB_PORT=27017
      - RUN_AS_USER=user
      ##- ENABLE_CHOWN=true
    env_file:
      - env/global.env
      - env/api-master.env
      - env/api.env
    logging:
      options:
        max-size: 1g
