#filename: docker-compose-local-gpu.yml
version: '3.3'


volumes:
  mongo_db_data:

networks:
  anyvision:

services:

  mongodb:
    image: gcr.io/anyvision-training/mongo:3.6-jessie
    restart: always
    networks:
      anyvision:
        aliases:
          - mongodb.tls.ai
    #ports:
      #- "27017:27017"
    volumes:
      - mongo_db_data:/data/db
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - env/global.env
    logging:
      options:
        max-size: 1g



  migration_manager:
    image: gcr.io/anyvision-training/migration_manager:development
    #restart: always
    networks:
      anyvision:
        aliases:
          - apigateway.tls.ai
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /storage/migration_db_data:/var/tmp
    depends_on:
      - mongodb
    environment:
      - MONGO_DB_IP=mongodb.tls.ai
      - MONGO_DB_NAME=anyVision2
      - API_IP=api.tls.ai
      - RUN_AS_USER=user
      #- ENABLE_CHOWN=true
    env_file:
      - env/global.env
    logging:
      options:
        max-size: 1g
