#filename: docker-compose-cloud-gpu.yml
version: '3.3'


networks:
  prod:


services:


  if3t-be:
    image: gcr.io/anyvision-training/ift3-be:development
    restart: always
    networks:
      prod:
        aliases:
          - ifttt.tls.ai
    ports:
      - 3005:3005
    volumes:
      - /usr/local/share/ca-certificates:/usr/local/share/ca-certificates
      - /etc/localtime:/etc/localtime:ro
      #- /etc/timezone:/etc/timezone:ro
    environment:
      - MONGO_DB_IP=mongodb://mongodb.tls.ai
      - MONGO_DB_PORT=27017
      - PORT=3005
      - MONGO_DB_NAME=third_party_db
      - REDIS_HOST=redis.tls.ai
      - REDIS_PORT=6379
      - WEB_APP_PORT=3005
      - WEB_API_PORT=4200
      - RUN_AS_USER=user
      - ENABLE_DOCKERIZE=false
      - ENABLE_CHOWN=false
      - NODE_DEBUG_OPTION=--inspect=0.0.0.0:38391
    logging:
      options:
        max-size: 1g

  if3t-fe:
    image: gcr.io/anyvision-training/ift3-fe:development
    restart: always
    networks:
      prod:
        aliases:
        - ifttt.tls.ai
    ports:
    - 4200:4200
    volumes:
    - /usr/local/share/ca-certificates:/usr/local/share/ca-certificates
    - /etc/localtime:/etc/localtime:ro
    #- /etc/timezone:/etc/timezone:ro
    environment:
    - API_PORT=3005
    logging:
      options:
        max-size: 1g

