version: "3"

services:

  nginx:
    image: nginx:stable
    restart: always
    volumes:
      - /storage:/usr/share/nginx/html:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro 
    network_mode: host

  nginx-rtmp:
    image: gcr.io/anyvision-training/nginx-rtmp
    restart: always
    network_mode: host

  mongo:
    image: mongo:3.4-jessie
    restart: always
    volumes:
      - db_data:/data/db
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    network_mode: host

  api:
    image: gcr.io/anyvision-training/api:{{version_name}}
    restart: always
    network_mode: host
    depends_on:
      - mongo
    volumes:
      - /storage:/var/www/html
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - mongo_host=localhost
      - APP_IP=127.0.0.1
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000 || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 3

  backend:
    image: gcr.io/anyvision-training/backend:{{version_name}}
    restart: always
    network_mode: host
    volumes:
      - /home/user/license:/home/user/license:ro
      - /home/anyvision:/home/anyvision
      - /tmp/.X11-unix:/tmp/.X11-unix
      - pipe_data:/root/pipe_data
      - /storage:/var/www/html
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - DISPLAY=$DISPLAY
    env_file:
      - backend.env
#    sysctls:
#      - vm.swappiness=0
#      - vm.drop_caches=3
#      - fs.file-max=200000
    ulimits:
      nproc: 200000
      nofile:
        soft: 200000
        hard: 200000
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:4005/dashboards_status || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 3

  dashboard:
    image: gcr.io/anyvision-training/dashboard:{{version_name}}
    restart: always
    shm_size: 1024M
    network_mode: host
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /home/anyvision:/home/anyvision
      - /var/sftp/uploads:/home/anyvision/uploads
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - DISPLAY=$DISPLAY

volumes:
  db_data:
  pipe_data:
