#filename: docker-compose-apimaster.yml
version: '3.3'


volumes:
  mongo_db_data:
  redis_db_data:
  backend_data:
  api_gateway_keys:


networks:
  anyvision:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.14.0.0/16


services:


  dashboard-master:
    image: gcr.io/anyvision-training/dashboard-master:development
    restart: always
    networks:
      anyvision:
        aliases:
          - dashboard-master-${node_name:-localnode}.anyvision.local
    ports:
    #  - "443:443"
      - "80:80"
    volumes:
      - /usr/local/share/ca-certificates/anyvision:/usr/local/share/ca-certificates/anyvision
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - limit_rate_speed=0
      - master_api_ip=api-master.anyvision.local
      - master_api_username=admin
      - master_api_password=admin
    env_file:
      - env/global.env
    logging:
      options:
        max-size: 1g


 

  api-master:
    image: gcr.io/anyvision-training/api-master:development
    restart: always
    networks:
      anyvision:
        aliases:
          - api-master.anyvision.local
    ports:
      - "27183:27183"
    volumes:
      - /storage:/var/www/html
      - /usr/local/share/ca-certificates/anyvision:/usr/local/share/ca-certificates/anyvision
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - api_service_ip=api.anyvision.local
      - api_service_port=3000
      - MONGO_DB_IP=mongodb.anyvision.local
      - MONGO_DB_PORT=27017
      - RUN_AS_USER=user
      - ENABLE_CHOWN=false
    env_file:
      - env/global.env
      - env/api-master.env
      - env/api.env
    logging:
      options:
        max-size: 1g
