version: '2.2'

services:

  dslr:
    restart: always
    privileged: true
    networks:
      - anyvision
    image: gcr.io/anyvision-training/dslr
    volumes:
      - backend_data:/root/pipe_data
      - c:/anv/storage:/var/www/html
      - c:/anv/storage/logs:/var/www/html/logs
      - c:/anv/storage/cameraMount:/root/mount
    environment:
      - pipe_cpu_mode=true
    env_file:
      - env/dslr.env
      - env/backend.env
      - env/global.env


volumes:
  backend_data:

networks:
  anyvision:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.14.0.0/16
          gateway: 172.14.0.1
