version: "3"

services:

  nginx:
    image: nginx:stable
    restart: always
    volumes:
      - /storage:/usr/share/nginx/html:ro
      - /etc/localtime:/etc/localtime:ro
    network_mode: host

  nginx-rtmp:
    image: gcr.io/anyvision-training/nginx-rtmp
    restart: always
    network_mode: host

  mongo:
    image: mongo:3.4-jessie
    restart: always
    volumes:
      - db_data:/data/db
      - /etc/localtime:/etc/localtime:ro
    network_mode: host

  api:
    image: gcr.io/anyvision-training/api:{{version_number}}
    restart: always
    network_mode: host
    depends_on:
      - mongo
    volumes:
      - /storage/logs:/root/Dash-API/logs
      - /etc/localtime:/etc/localtime:ro
    environment:
      - mongo_host=localhost
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000 || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 3

  redis:
    image: redis:4-alpine
    restart: always
    network_mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro

  backend:
    image: gcr.io/anyvision-training/backend:{{version_number}}
    restart: always
    network_mode: host
    depends_on:
      - redis
    volumes:
      - /home/user/license:/home/user/license:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
      - pipe_data:/root/pipe_data
      - /storage/logs:/var/www/html/logs
      - /storage/frame_store:/var/www/html/frame_store
      - /storage/pipe_store:/var/www/html/pipe_store
      - /etc/localtime:/etc/localtime:ro
    environment:
      - DISPLAY=$DISPLAY
    env_file:
      - backend.env
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:4005/dashboards_status || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 3

  dashboard:
    image: gcr.io/anyvision-training/dashboard:{{version_number}}
    restart: always
    shm_size: 1024M
    network_mode: host
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /home/anyvision:/home/anyvision
      - /var/sftp/uploads:/home/anyvision/uploads
      - /etc/localtime:/etc/localtime:ro
    environment:
      - DISPLAY=$DISPLAY

volumes:
  db_data:
  pipe_data:
