version: '3.3'

volumes:
  backend_data:

networks:
  anyvision:

services:

  dslr:
    restart: always
    networks:
      - anyvision
    image: gcr.io/anyvision-training/dslr
    volumes:
      - backend_data:/root/pipe_data
      - /storage:/var/www/html
      - /storage/logs:/var/www/html/logs
      - /storage/cameraMount:/root/mount
    environment:
      - pipe_cpu_mode=true
    env_file:
      - env/dslr.env
      - env/backend.env
      - env/global.env
