version: '3'

services:
  dslr:
    restart: always
    privileged: true
    #image: dslr:latest
    image: gcr.io/anyvision-training/dslr:master

    volumes:
      - /storage/dslr_db:/root/dslr_db
      - /storage/dslr_sync:/tmp/dslr_sync
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev/bus/usb/:/dev/bus/usb
      - /etc/localtime:/etc/localtime:ro

    environment:
      - DISPLAY=${DISPLAY:-:1}
      - GLOG_minloglevel=2
