#filename: docker-compose-local-win-cpu.yml
version: '3.3'


volumes:
  mongo_db_data:
  redis_db_data:
  backend_data:
  api_gateway_keys:


networks:
  anyvision:


services:


  nginx:
    image: gcr.io/anyvision-production/nginx-rtmp:ssl
    restart: always
    networks:
      anyvision:
        aliases:
          - nginx-${node_name:-localnode}.anyvision.local
    ports:
      - "1935:1935"
      #- "443:443"
      #- "80:80"
    volumes:
      - c:/anv/storage:/opt/nginx/html:ro
      - c:/anv/usr/local/share/ca-certificates/anyvision:/usr/local/share/ca-certificates/anyvision
    environment:
      - limit_rate_speed=0
    env_file:
      - env/global.env
    logging:
      options:
        max-size: 1g



  mongodb:
    image: gcr.io/anyvision-production/mongo:3.6-jessie
    restart: always
    networks:
      anyvision:
        aliases:
          - mongodb.anyvision.local
    #ports:
      #- "27017:27017"
    volumes:
      - mongo_db_data:/data/db
    env_file:
      - env/global.env
    logging:
      options:
        max-size: 1g



  redis:
    image: gcr.io/anyvision-production/redis:latest
    restart: always
    networks:
      anyvision:
        aliases:
          - redis.anyvision.local
    sysctls:
      - net.core.somaxconn=511
    volumes:
      - redis_db_data:/data:rw
    logging:
      options:
        max-size: 1g



  apigateway:
    image: gcr.io/anyvision-production/api-gateway:1.19.1
    restart: always
    networks:
      anyvision:
        aliases:
          - apigateway.anyvision.local
    ports:
      - "9443:9443"
    volumes:
      - c:/anv/storage:/var/www/html
      - api_gateway_keys:/home/user/api-gateway/config/keys
      - c:/anv/usr/local/share/ca-certificates/anyvision:/usr/local/share/ca-certificates/anyvision
    depends_on:
      - redis
    environment:
      - GATEWAY_HOST=apigateway.anyvision.local
      - API_HOST=api.anyvision.local
      - DASH_API_URL=https://api.anyvision.local:5443
      - GATEWAY_SECURE_URL=https://apigateway.anyvision.local:9443
      - GATEWAY_URL=http://apigateway.anyvision.local:8080
      - REDIS_HOST=redis.anyvision.local
      - RUN_AS_USER=user
      - ENABLE_CHOWN=false
    env_file:
      - env/api-gateway.env
      - env/global.env
    logging:
      options:
        max-size: 1g



  api:
    image: gcr.io/anyvision-production/api:1.19.1
    restart: always
    networks:
      anyvision:
        aliases:
          - api.anyvision.local
    ports:
      - "5443:5443"
    volumes:
      - c:/anv/storage:/var/www/html
      - c:/anv/usr/local/share/ca-certificates/anyvision:/usr/local/share/ca-certificates/anyvision
    environment:
      - API_IP=api.anyvision.local
      - MONGO_DB_IP=mongodb.anyvision.local
      - CA_HOST=apigateway.anyvision.local
      - MASS_IMPORT_IP=reid-${node_name:-localnode}.anyvision.local          ### use this configuration to configure localhost reid service
      - RUN_AS_USER=user
      - ENABLE_CHOWN=false
    env_file:
      - env/global.env
      - env/api.env
    logging:
      options:
        max-size: 1g



  backend:
    image: gcr.io/anyvision-production/backend-cpu-pyconcrete:1.19.1
    restart: always
    privileged: true    ## FOR ACCESSING DEVICES - NOT HOT-PLUGGABLE
    networks:
      anyvision:
        aliases:
          - proc-${node_name:-localnode}.anyvision.local
          - reid-${node_name:-localnode}.anyvision.local
          - coll-${node_name:-localnode}.anyvision.local
          - arch-${node_name:-localnode}.anyvision.local
    ports:
      #- "4005:4005"
      #- "9067:9067"
      #- "9068:9068"
      #- "9069:9069"
      - "5000-5025:5000-5025/udp"                                            ### for remote VMS rtsp connections
    volumes:
      - c:/anv/home/user/license:/home/user/license:ro
      - backend_data:/root/pipe_data
      - c:/anv/storage:/var/www/html
      - c:/anv/usr/local/share/ca-certificates/anyvision:/usr/local/share/ca-certificates/anyvision
    environment:
      - pipe_cpu_mode=true
      - DISPLAY=10.0.75.1:0.0
      - external_ip=proc-${node_name:-localnode}.anyvision.local
      - storage_ip=nginx-${node_name:-localnode}.anyvision.local
      - frame_store_storage_ip=nginx-${node_name:-localnode}.anyvision.local
      - redis_host=127.0.0.1
      - api_service_ip=api.anyvision.local
      - mongodb_host=mongodb.anyvision.local
      ########################################################################## use the configuration below to configure localhost services
      - reid_service_ip=reid-${node_name:-localnode}.anyvision.local
      - collate_service_ip=coll-${node_name:-localnode}.anyvision.local
      - track_archive_service_ip=arch-${node_name:-localnode}.anyvision.local
      ########################################################################## use the configuration below to configure the "b" server(s) hostname(s) in a/b architecture
      #- reid_service_ip=reid-b.anyvision.local
      #- collate_service_ip=coll-b.anyvision.local
      #- track_archive_service_ip=arch-b.anyvision.local
    env_file:
      - env/backend.env
      - env/global.env
    logging:
      options:
        max-size: 1g
    ipc: host



  dashboard:
    image: gcr.io/anyvision-production/dashboard:1.19.1
    restart: always
    privileged: true   ## FOR ACCESSING DEVICES - NOT HOT-PLUGGABLE
    networks:
      - anyvision
    shm_size: 1024M
    volumes:
      - c:/anv/storage/sftp_data:/sftp:rw
      - c:/anv/usr/local/share/ca-certificates/anyvision:/usr/local/share/ca-certificates/anyvision:ro
      - c:/anv/storage/share:/home/user/share:rw
    environment:
      - DISPLAY=10.0.75.1:0.0
      - ssl=true
      - GATEWAY_HOST=apigateway.anyvision.local
      - RUN_AS_USER=user
      - ENABLE_CHOWN=false
      - isPersonEnabled=false
    env_file:
      - env/global.env
      - env/api-gateway.env
      - env/dashboard.env
    logging:
      options:
        max-size: 1g
    ipc: host
