#filename: docker-compose-apimaster.yml
version: '3.3'


networks:
  prod:


services:


  dashboard-master:
    image: gcr.io/anyvision-training/dashboard-master:development
    restart: always
    networks:
      prod:
        aliases:
          - dashboard-master-localnode.tls.ai
    ports:
      #- "443:443"
      - "80:80"
    volumes:
      - /usr/local/share/ca-certificates:/usr/local/share/ca-certificates
      - /etc/localtime:/etc/localtime:ro
      #- /etc/timezone:/etc/timezone:ro
    environment:
      - limit_rate_speed=0
      - master_api_ip=api-master.tls.ai
      - master_api_username=admin
      - master_api_password=admin
    env_file:
      - env/global.env
    logging:
      options:
        max-size: 1g



  api-master:
    image: gcr.io/anyvision-training/api-master:development
    restart: always
    networks:
      prod:
        aliases:
          - api-master.tls.ai
    ports:
      - "27183:27183"
      - "38383:38383"
    volumes:
      - /storage:/var/www/html
      - /usr/local/share/ca-certificates:/usr/local/share/ca-certificates
      - /etc/localtime:/etc/localtime:ro
      #- /etc/timezone:/etc/timezone:ro
    environment:
      - NODE_DEBUG_OPTION=--inspect=0.0.0.0:38383
      - API_MASTER_PORT=27183
      - SELF_API_HOST=api.tls.ai
      - SELF_API_PORT=3000
      - MONGO_DB_IP=mongodb.tls.ai
      - MONGO_DB_PORT=27017
      - RUN_AS_USER=user
      #- ENABLE_CHOWN=false
    env_file:
      - env/global.env
      - env/api-master.env
    logging:
      options:
        max-size: 1g


 master-sync-service:
   image: gcr.io/anyvision-training/master-sync-service:development
   restart: always
   #network_mode: "host"       ## REQUIRED FOR MULTICAST BROADCASTING
   hostname: master-sync-service
   #command: --disable-services --no-exitkills --debug sleep infinity       ### development mode  - disable chaperone init
   networks:
     prod:
       aliases:
         - master-sync-service.tls.ai
   volumes:
     - /usr/local/share/ca-certificates:/usr/local/share/ca-certificates
     - /etc/localtime:/etc/localtime:ro
   depends_on:
     - api
   environment:
     #- ENABLE_DOCKERIZE=false
     - ENABLE_CHOWN=false
   env_file:
     - env/global.env
     - env/master-sync-service.env
   logging:
     options:
       max-size: 1g
