#filename: docker-compose-local-gpu.yml
version: '3.3'


volumes:
  mongo_db_data:

networks:
  anyvision:

services:

  mongodb:
    image: gcr.io/anyvision-production/mongo:3.6-jessie
    restart: always
    networks:
      anyvision:
        aliases:
          - mongodb.anyvision.local
    #ports:
      #- "27017:27017"
    volumes:
      - mongo_db_data:/data/db
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - env/global.env
    logging:
      options:
        max-size: 1g



  migration_db:
    image: gcr.io/anyvision-training/migration_manager:1.19.4
    #restart: always
    networks:
      anyvision:
        aliases:
          - apigateway.anyvision.local
    volumes:
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - mongodb
    environment:
      - MONGO_DB_IP=mongodb.anyvision.local
      - DB_NAME=anyVision2
      - RUN_AS_USER=user
      - ENABLE_CHOWN=false
    env_file:
      - env/global.env
    logging:
      options:
        max-size: 1g
