#filename: docker-compose-local-cpu.yml
version: '3.3'


volumes:
  mongo_db_data:
  redis_db_data:
  backend_data:
  api_gateway_keys:
  consul_data:


networks:
  anyvision:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.14.0.0/16


services:


  # coredns:
  #   image: coredns/coredns
  #   command: -conf /conf/Corefile
  #   restart: always
  #   networks:
  #     anyvision:
  #       ipv4_address: 172.14.0.250
  #   ports:
  #     - "127.0.0.1:53:53/udp"                                                ### replace 127.0.0.1 bind address with server external IP for listening to remote connections (A/B config)
  #     - "127.0.0.1:53:53/tcp"                                                ### replace 127.0.0.1 bind address with server external IP for listening to remote connections (A/B config)
  #     - "9153:9153/tcp"
  #   volumes:
  #     - ./coredns/Corefile:/conf/Corefile
  #     - ./coredns/db.anyvision.local:/conf/db.anyvision.local
  #   cap_drop:
  #     - ALL
  #   cap_add:
  #     - NET_BIND_SERVICE
  #   read_only: true
  #
  #
  #
  # consul-bootstrap:
  #   image: consul
  #   restart: always
  #   networks:
  #     - anyvision
  #   ports:
  #     - "8300:8300"
  #     - "8400:8400"
  #     - "8500:8500"
  #     - "172.14.0.1:53:8600/udp"
  #     - "${HOST_EXTERNAL_IP}:53:8600/udp"
  #   command:
  #     - "agent"
  #     - "-server"
  #     - "-bootstrap"
  #     - "-ui"
  #     - "-data-dir=/tmp"
  #     - "-advertise=${HOST_EXTERNAL_IP}"    ### Advertise using host environment variable ${HOST_EXTERNAL_IP}, so that we could do `curl ${HOST_EXTERNAL_IP}:8500/v1/catalog/services`
  #     - "-client=0.0.0.0"
  #     - "-node=bootstrap-node"
  #     - "-recursor=8.8.8.8"
  #     - "-domain=anyvision.local"
  #   volumes:
  #     - consul_data:/tmp/consul
  #   environment:
  #     - SERVICE_IGNORE=always               ### Ignore this container from Registrator
  #     - CONSUL_ALLOW_PRIVILEGED_PORTS=
  #   logging:
  #     options:
  #       max-size: 1g
  #
  #
  #
  # registrator:
  #   image: gliderlabs/registrator
  #   command: ["-ip", "${HOST_EXTERNAL_IP}", "consul://consul-bootstrap:8500"]
  #   networks:
  #     - anyvision
  #   depends_on:
  #     - consul-bootstrap
  #   volumes:
  #     - /var/run/docker.sock:/tmp/docker.sock
  #   logging:
  #     options:
  #       max-size: 1g



  guacamole:
    image: gcr.io/anyvision-training/guacamole:0.9.14
    restart: always
    networks:
      - anyvision
    ports:
      - "8080:8080"
    volumes:
      - ./guacamole/user-mapping-local.xml:/etc/guacamole/user-mapping.xml
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    env_file:
      - env/global.env
    logging:
      options:
        max-size: 1g



  sftp:
    image: atmoz/sftp
    restart: always
    networks:
      - anyvision
    volumes:
      - /storage/sftp_data:/home/user
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    command: user:pass:2000:2000:files
    env_file:
      - env/global.env
    logging:
      options:
        max-size: 1g



  nginx:
    image: gcr.io/anyvision-training/nginx-rtmp:ssl
    restart: always
    networks:
      anyvision:
        aliases:
          - nginx-${node_name:-localnode}.anyvision.local
    ports:
      - "1935:1935"
      #- "443:443"
      #- "80:80"
    volumes:
      - /storage:/opt/nginx/html:ro
      - /usr/local/share/ca-certificates/anyvision:/usr/local/share/ca-certificates/anyvision
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    env_file:
      - env/global.env
    logging:
      options:
        max-size: 1g



  cron:
    image: gcr.io/anyvision-training/supercronic:latest
    restart: always
    networks:
      anyvision:
        aliases:
          - cron-${node_name:-localnode}.anyvision.local
    volumes:
      - /storage:/var/www/html
      - ./env/crontab:/etc/crontab
      - ./migration:/root/migration
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - TO_DATE_TRACK_DELETE=30
    env_file:
      - env/global.env
    logging:
      options:
        max-size: 1g



  rabbitmq:
    image: gcr.io/anyvision-training/rabbitmq:latest
    restart: always
    networks:
      anyvision:
        aliases:
          - rabbitmq.anyvision.local
    ports:
     - "5761:5761"
     - "5762:5762"
     - "15761:15761"
    volumes:
      - /storage/rabbitmq:/var/lib/rabbitmq
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    env_file:
      - env/global.env
    logging:
      options:
        max-size: 1g



  mongodb:
    image: gcr.io/anyvision-training/mongo:3.6-jessie
    restart: always
    networks:
      anyvision:
        aliases:
          - mongodb.anyvision.local
    #ports:
    #  - "27017:27017"
    volumes:
      - mongo_db_data:/data/db
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    env_file:
      - env/global.env
    logging:
      options:
        max-size: 1g



  redis:
    image: gcr.io/anyvision-training/redis:latest
    restart: always
    networks:
      - anyvision
    sysctls:
      - net.core.somaxconn=511
    volumes:
      - redis_db_data:/data:rw
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    logging:
      options:
        max-size: 1g



  broadcaster:
    image: gcr.io/anyvision-training/broadcaster:development
    restart: always
    hostname: broadcaster
    networks:
      anyvision:
        aliases:
          - broadcaster.anyvision.local
    #dns: 172.14.0.1                                                          ### internal DNS server address, replace this with external IP of CoreDNS/Consul server (A/B config)
    volumes:
      - /usr/local/share/ca-certificates/anyvision:/usr/local/share/ca-certificates/anyvision
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    depends_on:
      - api
    environment:
      - RUN_AS_USER=user
      - ENABLE_CHOWN=false
    env_file:
      - env/global.env
      - env/broadcaster.env
    logging:
      options:
        max-size: 1g



  apigateway:
    image: gcr.io/anyvision-training/api-gateway:development
    restart: always
    networks:
      anyvision:
        aliases:
          - apigateway.anyvision.local
    ports:
      - "9443:9443"
    #dns: 172.14.0.1                                                          ### internal DNS server address, replace this with external IP of CoreDNS/Consul server (A/B config)
    volumes:
      - /storage:/var/www/html
      - api_gateway_keys:/home/user/api-gateway/config/keys
      - /usr/local/share/ca-certificates/anyvision:/usr/local/share/ca-certificates/anyvision
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    depends_on:
      - redis
    environment:
      - RUN_AS_USER=user
      - ENABLE_CHOWN=false
    env_file:
      - env/api-gateway.env
      - env/global.env
    logging:
      options:
        max-size: 1g



  api-master:
    image: gcr.io/anyvision-training/api-master:development
    restart: always
    networks:
      anyvision:
        aliases:
          - api-master.anyvision.local
    #dns: 172.14.0.1  ### internal DNS server address, replace this with external IP of CoreDNS/Consul server (A/B config)
    volumes:
      - /storage:/var/www/html
      - /usr/local/share/ca-certificates/anyvision:/usr/local/share/ca-certificates/anyvision
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - RUN_AS_USER=user
      - ENABLE_CHOWN=false
      #- TZ=Etc/UTC    ## DO NOT CHANGE
    env_file:
      - env/global.env
      - env/api-master.env
    logging:
      options:
        max-size: 1g



  api:
    image: gcr.io/anyvision-training/api:development
    restart: always
    networks:
      anyvision:
        aliases:
          - api.anyvision.local
    ports:
      - "5443:5443"
    #dns: 172.14.0.1                                                          ### internal DNS server address, replace this with external IP of CoreDNS/Consul server (A/B config)
    volumes:
      - /storage:/var/www/html
      - /usr/local/share/ca-certificates/anyvision:/usr/local/share/ca-certificates/anyvision
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - API_IP=api.anyvision.local
      - MONGO_DB_IP=mongodb.anyvision.local
      - CA_HOST=apigateway.anyvision.local
      - RUN_AS_USER=user
      - ENABLE_CHOWN=false
      - MASS_IMPORT_IP=reid-${node_name:-localnode}.anyvision.local          ### use this configuration to configure localhost reid service
      #- MASS_IMPORT_IP=reid-b.anyvision.local                               ### use this configuration to configure the "b" server reid service in a/b architecture
      #- TZ=Etc/UTC    ## DO NOT CHANGE
    env_file:
      - env/global.env
      - env/api.env
    logging:
      options:
        max-size: 1g



  backend:
    image: gcr.io/anyvision-training/backend-cpu:development
    restart: always
    privileged: true   ## FOR ACCESSING DEVICES - NOT HOT-PLUGGABLE
    networks:
      anyvision:
        aliases:
          - proc-${node_name:-localnode}.anyvision.local
          - reid-${node_name:-localnode}.anyvision.local
          - coll-${node_name:-localnode}.anyvision.local
          - arch-${node_name:-localnode}.anyvision.local
    ports:
      #- "4005:4005"
      #- "9067:9067"
      #- "9068:9068"
      #- "9069:9069"
      - "5000-5025:5000-5025/udp"                                            ### for remote VMS rtsp connections
    #dns: 172.14.0.1                                                          ### internal DNS server address, replace this with external IP of CoreDNS/Consul server (A/B config)
    volumes:
      - /home/user/license:/home/user/license:ro
      - backend_data:/root/pipe_data
      - /storage:/var/www/html
      - /usr/local/share/ca-certificates/anyvision:/usr/local/share/ca-certificates/anyvision
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - pipe_cpu_mode=true
      - DISPLAY                                                              ### local display mode - do not forget to run "xhost +" as your local host user (not as root)
      - external_ip=proc-${node_name:-localnode}.anyvision.local
      - storage_ip=nginx-${node_name:-localnode}.anyvision.local
      - frame_store_storage_ip=nginx-${node_name:-localnode}.anyvision.local
      - redis_host=127.0.0.1
      - api_service_ip=api.anyvision.local
      - mongodb_host=mongodb.anyvision.local
      ########################################################################## use the configuration below to configure localhost services
      - reid_service_ip=reid-${node_name:-localnode}.anyvision.local
      - collate_service_ip=coll-${node_name:-localnode}.anyvision.local
      - track_archive_service_ip=arch-${node_name:-localnode}.anyvision.local
      ########################################################################## use the configuration below to configure the "b" server(s) hostname(s) in a/b architecture
      #- reid_service_ip=reid-b.anyvision.local
      #- collate_service_ip=coll-b.anyvision.local
      #- track_archive_service_ip=arch-b.anyvision.local
    env_file:
      - env/backend.env
      - env/global.env
    logging:
      options:
        max-size: 1g
    ipc: host



  dashboard:
    image: gcr.io/anyvision-training/dashboard:development
    restart: always
    privileged: true   ## FOR ACCESSING DEVICES - NOT HOT-PLUGGABLE
    networks:
      - anyvision
    #dns: 172.14.0.1                                                          ### internal DNS server address, replace this with external IP of CoreDNS/Consul server (A/B config)
    shm_size: 1024M
    volumes:
      - /storage/sftp_data:/sftp:rw
      - /usr/local/share/ca-certificates/anyvision:/usr/local/share/ca-certificates/anyvision:ro
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /media:/home/user/media:ro
      - /storage/share:/home/user/share:rw
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - DISPLAY                                                              ### local display mode - do not forget to run "xhost +" as your local host user (not as root)
      - ssl=true
      - RUN_AS_USER=user
      - ENABLE_CHOWN=false
    env_file:
      - env/global.env
      - env/api-gateway.env
      - env/dashboard.env
    logging:
      options:
        max-size: 1g
    ipc: host
