#filename: docker-compose-memsql-addon.yml
version: '3.3'


networks:
  prod:
    ipam:
      driver: default
      config:
      -
        subnet: 172.30.30.0/24

services:


  memsql:
    image: gcr.io/anyvision-training/memsql:19.01
    restart: always
    networks:
      prod:
        aliases:
          - memsql.tls.ai
    ports:
      - "3306:3306"
    deploy:
      resources:
        limits:
          memory: 128g
    volumes:
      - /ssd/memsql:/var/lib/memsql
      - /etc/localtime:/etc/localtime:ro
      #- /etc/timezone:/etc/timezone:ro
    environment:
      - LICENSE_KEY=BDk3ZmFhNGU3YmJmOTQ5N2I5N2RmY2E4ZWEzZTAxYjVlAAAAAAAAAAAAAAIAAAAAAAQwNQIZAJGgtcrXzs18QzlKPsIo5SNnwVxqxH6gEwIYbWq/m+E3/flYcFfIm3ERvsxjtlbaz7O5AA==
      - MEMSQL_NODE_ROLE=AIO
    logging:
      options:
        max-size: 1g



  memsql-master:
    image: gcr.io/anyvision-training/memsql:19.01
    restart: always
    networks:
      prod:
        aliases:
          - memsql-master.tls.ai
    ports:
      - "3306:3306"
    deploy:
      resources:
        limits:
          memory: 4g
    volumes:
      - /ssd/memsql-master:/var/lib/memsql
      - /etc/localtime:/etc/localtime:ro
      #- /etc/timezone:/etc/timezone:ro
    environment:
      - LICENSE_KEY=BDk3ZmFhNGU3YmJmOTQ5N2I5N2RmY2E4ZWEzZTAxYjVlAAAAAAAAAAAAAAIAAAAAAAQwNQIZAJGgtcrXzs18QzlKPsIo5SNnwVxqxH6gEwIYbWq/m+E3/flYcFfIm3ERvsxjtlbaz7O5AA==
      - MEMSQL_MASTER_HOST=memsql-master.tls.ai
      - MEMSQL_AGGREGATOR_HOST=memsql-aggregator.tls.ai
      - MEMSQL_LEAF_HOST_1=memsql-leaf-1.tls.ai
      - MEMSQL_LEAF_HOST_2=memsql-leaf-2.tls.ai
      - MEMSQL_NODE_ROLE=MASTER
    logging:
      options:
        max-size: 1g



  memsql-aggregator:
    image: gcr.io/anyvision-training/memsql:19.01
    restart: always
    networks:
      prod:
        aliases:
          - memsql-aggregator.tls.ai
    ports:
      - "3306:3306"
    deploy:
      resources:
        limits:
          memory: 4g
    volumes:
      - /ssd/memsql-aggregator:/var/lib/memsql
      - /etc/localtime:/etc/localtime:ro
      #- /etc/timezone:/etc/timezone:ro
    environment:
      - MEMSQL_NODE_ROLE=AGGREGATOR
    logging:
      options:
        max-size: 1g



  memsql-leaf-1:
    image: gcr.io/anyvision-training/memsql:19.01
    restart: always
    networks:
      prod:
        aliases:
          - memsql-leaf-1.tls.ai
    ports:
      - "3306:3306"
    deploy:
      resources:
        limits:
          memory: 60g
    volumes:
      - /ssd/memsql-leaf-1:/var/lib/memsql
      - /etc/localtime:/etc/localtime:ro
      #- /etc/timezone:/etc/timezone:ro
    environment:
      - MEMSQL_NODE_ROLE=LEAF
    logging:
      options:
        max-size: 1g



  memsql-leaf-2:
    image: gcr.io/anyvision-training/memsql:19.01
    restart: always
    networks:
      prod:
        aliases:
          - memsql-leaf-2.tls.ai
    ports:
      - "3306:3306"
    deploy:
      resources:
        limits:
          memory: 60g
    volumes:
      - /ssd/memsql-leaf-2:/var/lib/memsql
      - /etc/localtime:/etc/localtime:ro
      #- /etc/timezone:/etc/timezone:ro
    environment:
      - MEMSQL_NODE_ROLE=LEAF
    logging:
      options:
        max-size: 1g
