#filename: docker-compose-liveness-gpu.yml
version: '3.3'


networks:
  prod:
    ipam:
      driver: default
      config:
      -
        subnet: 172.30.30.0/24



services:


  liveness-service:
    image: gcr.io/anyvision-production/liveness-service:development
    restart: always
    networks:
      prod:
        aliases:
          - liveness-service.tls.ai
    ports:
      - "50051:50051"
    volumes:
      - /usr/local/share/ca-certificates:/usr/local/share/ca-certificates
      - /etc/localtime:/etc/localtime:ro
      - /storage/liveness-logs:/var/log/liveness-logs:rw
    environment:
      - HOST_IP=liveness-service.tls.ai
      #gpu on slot 0
      - GPU_INSTANCE=0
      - RUN_AS_USER=user
    env_file:
      - env/liveness-service.env
    logging:
      options:
        max-size: 1g
