version: '3'

services:
  dslr:
    restart: always
    privileged: true
    image: gcr.io/anyvision-training/dslr:master
    volumes:
      - /storage/dslr_db:/root/dslr_db
      - /storage/dslr_sync:/tmp/dslr_sync
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev/bus/usb/:/dev/bus/usb
      - /etc/localtime:/etc/localtime:ro
    environment:
      - CAMERA_ID=dslr_camera
      - API_IP=127.0.0.1
      - API_PORT=3000
      - API_ROUTE=internal/detections/faces
      - DB_FILE_PATH=/root/dslr_db/dslr.db
      - MIN_FACE_SIZE=80
      - PYRAMID_FACTOR=0.49
      - DISPLAY=${DISPLAY:-:1}
      - GLOG_minloglevel=2
