#filename: docker-compose-cloud-gpu.yml
version: '3.3'


volumes:
  mongo_db_data:
  redis_db_data:
  backend_data:
  api_gateway_keys:


networks:
  anyvision:


services:


  guacamole:
    image: gcr.io/anyvision-production/guacamole:0.9.14
    restart: always
    networks:
      - anyvision
    ports:
      - "8080:8080"
    volumes:
      - ./guacamole/user-mapping-cloud.xml:/etc/guacamole/user-mapping.xml
    environment:
      - TZ=${TZ:-UTC}
      - GUACD_LOGLEVEL=info
    env_file:
      - env/global.env
    logging:
      options:
        max-size: 1g



  sftp:
    image: gcr.io/anyvision-production/sftp:alpine
    restart: always
    networks:
      - anyvision
    volumes:
      - /storage/sftp_data:/home/user
    command: user:pass:2000:2000:files
    environment:
      - TZ=${TZ:-UTC}
    env_file:
      - env/global.env
    logging:
      options:
        max-size: 1g



  nginx:
    image: gcr.io/anyvision-production/nginx-rtmp:ssl
    restart: always
    networks:
      anyvision:
        aliases:
          - nginx-${node_name:-localnode}.anyvision.local
    ports:
      - "1935:1935"
      #- "443:443"
      #- "80:80"
    volumes:
      - /storage:/opt/nginx/html:ro
      - /usr/local/share/ca-certificates/anyvision:/usr/local/share/ca-certificates/anyvision
    environment:
      - TZ=${TZ:-UTC}
      - limit_rate_speed=0
    env_file:
      - env/global.env
    logging:
      options:
        max-size: 1g



  cron:
    image: gcr.io/anyvision-production/supercronic:latest
    restart: always
    networks:
      anyvision:
        aliases:
          - cron-${node_name:-localnode}.anyvision.local
    volumes:
      - /storage:/var/www/html
      - ./crontab/site_crontab:/etc/crontabs/crontab
    environment:
      - TZ=${TZ:-UTC}
      - TO_DATE_TRACK_DELETE=30
    logging:
      options:
        max-size: 1g



  rabbitmq:
    image: gcr.io/anyvision-production/rabbitmq:latest
    restart: always
    networks:
      anyvision:
        aliases:
          - rabbitmq.anyvision.local
    #ports:
      #- "5761:5761"
      #- "15761:15761"
    volumes:
      - /storage/rabbitmq:/var/lib/rabbitmq
    environment:
      - TZ=${TZ:-UTC}
    env_file:
      - env/global.env
    logging:
      options:
        max-size: 1g



  mongodb:
    image: gcr.io/anyvision-production/mongo:3.6-jessie
    restart: always
    networks:
      anyvision:
        aliases:
          - mongodb.anyvision.local
    #ports:
      #- "27017:27017"
    volumes:
      - mongo_db_data:/data/db
    environment:
      - TZ=${TZ:-UTC}
    env_file:
      - env/global.env
    logging:
      options:
        max-size: 1g



  redis:
    image: gcr.io/anyvision-production/redis:latest
    restart: always
    networks:
      anyvision:
        aliases:
          - redis.anyvision.local
    sysctls:
      - net.core.somaxconn=511
    volumes:
      - redis_db_data:/data:rw
    environment:
      - TZ=${TZ:-UTC}
    logging:
      options:
        max-size: 1g



  broadcaster:
    image: gcr.io/anyvision-production/broadcaster:1.19.3
    restart: always
    hostname: broadcaster
    networks:
      anyvision:
        aliases:
          - broadcaster.anyvision.local
    volumes:
      - /usr/local/share/ca-certificates/anyvision:/usr/local/share/ca-certificates/anyvision
    depends_on:
      - api
    environment:
      - TZ=${TZ:-UTC}
      - api_service_ip=api.anyvision.local
      - BCAST_SOCKETIO_API_URL=https://api.anyvision.local:5443
      - RUN_AS_USER=user
      - ENABLE_CHOWN=false
    env_file:
      - env/global.env
      - env/broadcaster.env
    logging:
      options:
        max-size: 1g



  apigateway:
    image: gcr.io/anyvision-production/api-gateway:1.19.3
    restart: always
    networks:
      anyvision:
        aliases:
          - apigateway.anyvision.local
    ports:
      - "9443:9443"
    volumes:
      - /storage:/var/www/html
      - api_gateway_keys:/home/user/api-gateway/config/keys
      - /usr/local/share/ca-certificates/anyvision:/usr/local/share/ca-certificates/anyvision
    depends_on:
      - redis
    environment:
      - TZ=${TZ:-UTC}
      - GATEWAY_HOST=apigateway.anyvision.local
      - API_HOST=api.anyvision.local
      - DASH_API_URL=https://api.anyvision.local:5443
      - GATEWAY_SECURE_URL=https://apigateway.anyvision.local:9443
      - GATEWAY_URL=http://apigateway.anyvision.local:8080
      - REDIS_HOST=redis.anyvision.local
      - RUN_AS_USER=user
      - ENABLE_CHOWN=false
      - ENABLE_CREATE_SSL=true
    env_file:
      - env/api-gateway.env
      - env/global.env
    logging:
      options:
        max-size: 1g



  api:
    image: gcr.io/anyvision-production/api:1.19.3
    restart: always
    networks:
      anyvision:
        aliases:
          - api.anyvision.local
    ports:
      - "5443:5443"
    volumes:
      - /storage:/var/www/html
      - /usr/local/share/ca-certificates/anyvision:/usr/local/share/ca-certificates/anyvision
    environment:
      - TZ=${TZ:-UTC}
      - API_IP=api.anyvision.local
      - MONGO_DB_IP=mongodb.anyvision.local
      - CA_HOST=apigateway.anyvision.local
      - MASS_IMPORT_IP=reid-${node_name:-localnode}.anyvision.local          ### use this configuration to configure localhost reid service
      - RUN_AS_USER=user
      - ENABLE_CHOWN=false
    env_file:
      - env/global.env
      - env/api.env
    logging:
      options:
        max-size: 1g



  backend:
    image: gcr.io/anyvision-production/backend-pyconcrete:1.19.3
    restart: always
    networks:
      anyvision:
        aliases:
          - proc-${node_name:-localnode}.anyvision.local
          - reid-${node_name:-localnode}.anyvision.local
          - coll-${node_name:-localnode}.anyvision.local
          - arch-${node_name:-localnode}.anyvision.local
    ports:
      #- "4005:4005"
      #- "9067:9067"
      #- "9068:9068"
      #- "9069:9069"
      - "5000-5025:5000-5025/udp"                                            ### for remote VMS rtsp connections
    volumes:
      - /home/user/license:/home/user/license:ro
      - backend_data:/root/pipe_data
      - /storage:/var/www/html
      - /usr/local/share/ca-certificates/anyvision:/usr/local/share/ca-certificates/anyvision
      - /dev/shm:/dev/shm:rw
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    environment:
      - TZ=${TZ:-UTC}
      - DISPLAY=:0
      - external_ip=proc-${node_name:-localnode}.anyvision.local
      - storage_ip=nginx-${node_name:-localnode}.anyvision.local
      - frame_store_storage_ip=nginx-${node_name:-localnode}.anyvision.local
      - redis_host=127.0.0.1
      - api_service_ip=api.anyvision.local
      - mongodb_host=mongodb.anyvision.local
      ########################################################################## use the configuration below to configure localhost services
      - reid_service_ip=reid-${node_name:-localnode}.anyvision.local
      - collate_service_ip=coll-${node_name:-localnode}.anyvision.local
      - track_archive_service_ip=arch-${node_name:-localnode}.anyvision.local
      ########################################################################## use the configuration below to configure the "b" server(s) hostname(s) in a/b architecture
      #- reid_service_ip=reid-b.anyvision.local
      #- collate_service_ip=coll-b.anyvision.local
      #- track_archive_service_ip=arch-b.anyvision.local
    env_file:
      - env/backend.env
      - env/global.env
    ipc: host
    logging:
      options:
        max-size: 1g



  dashboard:
    image: gcr.io/anyvision-production/dashboard:1.19.3
    restart: always
    networks:
      - anyvision
    volumes:
      - /storage/sftp_data:/sftp:rw
      - /usr/local/share/ca-certificates/anyvision:/usr/local/share/ca-certificates/anyvision:ro
      - /media:/home/user/media:ro
      - /storage/share:/home/user/share:rw
      - /dev/shm:/dev/shm:rw
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    environment:
      - TZ=${TZ:-UTC}
      - DISPLAY=:0
      - ssl=true
      - GATEWAY_HOST=apigateway.anyvision.local
      - RUN_AS_USER=root
      - ENABLE_CHOWN=false
    env_file:
      - env/global.env
      - env/api-gateway.env
      - env/dashboard.env
    ipc: host
    logging:
      options:
        max-size: 1g



  desktop:
    image: gcr.io/anyvision-production/desktop
    restart: always
    privileged: true   ## FOR ACCESSING DEVICES - NOT HOT-PLUGGABLE
    networks:
      - anyvision
    volumes:
      - /storage/sftp_data:/sftp:ro
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /dev/shm:/dev/shm:rw
    environment:
      - TZ=${TZ:-UTC}
      - DISPLAY=:0
      - VNC_OPTIONS=-noshm -nodpms -noxdamage -shared -forever -passwd 123456 -rfbport 5900 -display :0
    env_file:
      - env/global.env
    ipc: host
    logging:
      options:
        max-size: 1g
