version: '3.3'

networks:
  monitor-net:
    ipam:
      driver: default
      config:
      -
        subnet: 172.30.35.0/24    
  prod:
    external:
      name: docker-compose_prod


volumes:
    prometheus_data:
    grafana_data:


services:



  prometheus:
    image: gcr.io/anyvision-production/prometheus:v2.3.2
    volumes:
      - ./prometheus/:/etc/prometheus:rw
      - prometheus_data:/prometheus:rw
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=10d'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    restart: always
    ports:
      - 9090:9090
    networks:
      - monitor-net
    logging:
      options:
        max-size: 1g
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '1gb'


  alertmanager:
    image: gcr.io/anyvision-production/alertmanager:v0.15.2
    volumes:
      - ./alertmanager:/etc/alertmanager:rw
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
      - '--log.level=debug'
      - '--web.external-url=http://devops.anyvision.co'
    #- '--web.route-prefix=/'
    #- '--web.listen-address=:9093'
    restart: always
    ports:
      - 9093:9093
    networks:
      - monitor-net
    environment:
      - ADMIN_USER=${ADMIN_USER:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
    logging:
      options:
        max-size: 1g
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '1gb'


  grafana:
    image: gcr.io/anyvision-production/grafana:5.2.2
    volumes:
      #- grafana_data:/var/lib/grafana:rw
      #- ./grafana/datasources:/etc/grafana/datasources:rw
      #- ./grafana/dashboards:/var/lib/grafana/dashboards:rw
      #- ./grafana/files/:/etc/grafana/files:rw
      - grafana_data:/var/lib/grafana:rw
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini:rw
      - ./grafana/provisioning:/etc/grafana/provisioning:rw
      - ./grafana/dashboards:/var/lib/grafana/dashboards:rw
    #entrypoint: /etc/grafana/files/setup.sh
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: always
    ports:
      - 3001:3001
    networks:
      - monitor-net
    depends_on:
      - prometheus
    logging:
      options:
        max-size: 1g
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '1gb'


          
  blackbox:
    image: gcr.io/anyvision-production/blackbox-exporter:v0.12.0
    restart: always
    ports:
      - "9115:9115"
    networks:
      - monitor-net
      - prod
    volumes:
      - ./blackbox-exporter:/config
    command:
      - '--config.file=/config/blackbox.yml'
      - '--log.level=debug'
    logging:
      options:
        max-size: 1g
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '1gb'
