version: '3.3'

networks:
  monitor-net:

volumes:
  nvidia_dcgm_exporter_date:

services:

  nodeexporter:
    image: gcr.io/anyvision-training/node-exporter:v0.16.0
    user: root
    privileged: true
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - nvidia_dcgm_exporter_date:/etc/node-exporter:ro
      #- /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc|docker|tmpfs)($$|/)'
      - '--collector.filesystem.ignored-fs-types=^/(aufs|cgroup|devpts|mqueue|nsfs|sysfs|proc|tmpfs|loop|shm|none|overlay)($$|/)'
      - '--collector.textfile.directory=/etc/node-exporter'
    restart: always
    ports:
      - 9100:9100
    networks:
      - monitor-net
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '1gb'
    logging:
      options:
        max-size: 1g

  cadvisor:
    image: gcr.io/anyvision-training/google-cadvisor:v0.30.2
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
      #- /cgroup:/cgroup:ro
      #- <path-where-nvml-is-present>:<path-where-nvml-is-present>
    restart: always
    ports:
      - 9101:9101
    networks:
      - monitor-net
    command:
      - '--port=9101'
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '1gb'
    logging:
      options:
        max-size: 1g

  nvidia-dcgm-exporter:
    image: gcr.io/anyvision-training/nvidia-dcgm-exporter
    restart: always
    privileged: true
    networks:
    - monitor-net
    volumes:
      - nvidia_dcgm_exporter_date:/run/prometheus
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '1gb'
    logging:
      options:
        max-size: 1g
