#filename: docker-compose-local-b.yml
version: '3.3'

volumes:
  backend_data:


networks:
  anyvision:
#    driver: bridge
#    ipam:
#      driver: default
#      config:
#        - subnet: 172.14.0.0/16


services:

  nginx:
    image: gcr.io/anyvision-production/nginx-rtmp:ssl
    restart: always
    networks:
      anyvision:
        aliases:
          - nginx-aXX.anyvision.local
    ports:
      - "1935:1935"
      - "443:443"
      - "80:80"
    volumes:
      - /storage:/opt/nginx/html:ro
      - /usr/local/share/ca-certificates/anyvision:/usr/local/share/ca-certificates/anyvision
    environment:
      - limit_rate_speed=0
    env_file:
      - ../../env/global.env
    logging:
      options:
        max-size: 1g

  cron:
    image: gcr.io/anyvision-production/supercronic:latest
    restart: always
    networks:
      anyvision:
        aliases:
        - cron-aXX.anyvision.local
    volumes:
      - /storage:/var/www/html
      - ../../crontab/a_site_crontab:/etc/crontabs/crontab
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    logging:
      options:
        max-size: 1g

  backend:
    image: 'gcr.io/anyvision-production/backend-pyconcrete:1.19.2'
    restart: always
    privileged: true
    #command: --disable-services --no-exitkills --debug sleep infinity       ### development mode - disable chaperone init
    networks:
      anyvision:
        aliases:
          - proc-aXX.anyvision.local
    extra_hosts:
      - "api.anyvision.local:<ip of b server>"
      - "apigateway.anyvision.local:<ip of b server>"
      - "mongodb.anyvision.local:<ip of b server>"
      - "reid-b.anyvision.local:<ip of b server>"
      - "coll-b.anyvision.local:<ip of b server>"
      - "arch-b.anyvision.local:<ip of b server>"
      - "nginx-b.anyvision.local:<ip of b server>"
    ports:
      - "4005:4005"
      - "9067:9067"
      - "9068:9068"
      - "9069:9069"
      - "5000-5025:5000-5025/udp"                                            ### for remote VMS rtsp connections
    #dns: <EXTERNAL_IP_OF_SERVER_B>                                          ### Enable when has coredns internal DNS server address, replace this with external IP of CoreDNS server (A/B config)
    volumes:
      - /home/user/license:/home/user/license:ro
      - backend_data:/root/pipe_data
      - /storage:/var/www/html
      - /usr/local/share/ca-certificates/anyvision:/usr/local/share/ca-certificates/anyvision
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /dev:/dev
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      #- /root/backend_trunk:/root/backend_trunk                             ### mount your local project directory to the container
    environment:
      - DISPLAY=${DISPLAY:-1}                                                               ### local display mode - do not forget to run "xhost +" as your local host user (not as root)
      - external_ip=proc-aXX.anyvision.local
      - storage_ip=nginx-b.anyvision.local
      - frame_store_storage_ip=nginx-aXX.anyvision.local
      - redis_host=127.0.0.1
      - api_service_ip=api.anyvision.local
      - mongodb_host=mongodb.anyvision.local
      - reid_service_ip=reid-b.anyvision.local
      - collate_service_ip=coll-b.anyvision.local
      - track_archive_service_ip=arch-b.anyvision.local
      - ENABLE_DOCKERIZE=false
      - ENABLE_REID_SERVICE=false
      - ENABLE_TRACK_ARCHIVE_SERVICE=false
      - ENABLE_COLLATE_SERVICE=false
      - ENABLE_XPRA_SERVICE=false
      - ENABLE_CRON_PIPE_IMG_TEMPORARY=false
    env_file:
      - ../../env/backend.env
      - ../../env/global.env
    logging:
      options:
        max-size: 1g
    ipc: host
