version: '2.3'


volumes:
  mongo_db_data:
  redis_db_data:
  backend_data:
  api_gateway_keys:



networks:
  anyvision:
    name: devs
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.14.0.0/16
          gateway: 172.14.0.1


services:


  coredns:
    image: coredns/coredns
    command: -conf /conf/Corefile
    runtime: runc
    restart: always
    networks:
      anyvision:
        ipv4_address: 172.14.0.250
    ports:
      - "127.0.0.1:53:53/udp"                                                ### replace 127.0.0.1 bind address with server external IP for listening to remote connections (A/B config)
      - "127.0.0.1:53:53/tcp"                                                ### replace 127.0.0.1 bind address with server external IP for listening to remote connections (A/B config)
      - "9153:9153/tcp"
    volumes:
      - $PWD/coredns/Corefile:/conf/Corefile
      - $PWD/coredns/db.anyvision.local:/conf/db.anyvision.local
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    read_only: true



  nginx:
    image: gcr.io/anyvision-training/nginx-rtmp:ssl
    runtime: runc
    restart: always
    networks:
      anyvision:
        aliases:
          - nginx-b.anyvision.local
    ports:
      - "1935:1935"
      - "443:443"
      - "80:80"
    volumes:
      - /storage:/opt/nginx/html:ro
      - /usr/local/share/ca-certificates/anyvision:/usr/local/share/ca-certificates/anyvision
    env_file:
      - env-v1.19/global.env
    logging:
      options:
        max-size: 1g



  mongodb:
    image: gcr.io/anyvision-training/mongo:3.6-jessie
    runtime: runc
    restart: always
    networks:
      anyvision:
        aliases:
          - mongodb.anyvision.local
    ports:
      - "27017:27017"
    volumes:
      - mongo_db_data:/data/db
    env_file:
      - env-v1.19/global.env
    logging:
      options:
        max-size: 1g



  redis:
    image: gcr.io/anyvision-training/redis:latest
    runtime: runc
    restart: always
    networks:
      - anyvision
    sysctls:
      - net.core.somaxconn=511
    volumes:
      - redis_db_data:/data:rw
    logging:
      options:
        max-size: 1g



  apigateway:
    image: gcr.io/anyvision-training/api-gateway:development
    runtime: runc
    restart: always
    #command: --disable-services --no-exitkills --debug sleep infinity       ### development mode - disable chaperone init
    networks:
      anyvision:
        aliases:
          - apigateway.anyvision.local
    ports:
      - "9443:9443"
      - "38391:38391"
    dns: 172.14.0.250                                                        ### internal DNS server address, replace this with external IP of CoreDNS server (A/B config)
    volumes:
      - /storage:/var/www/html
      - api_gateway_keys:/home/user/api-gateway/config/keys
      - /usr/local/share/ca-certificates/anyvision:/usr/local/share/ca-certificates/anyvision
      #- /home/anyvision/Projects/API-gateway:/home/user/api-gateway         ### mount your local project directory to the container
    depends_on:
      - redis
    environment:
      - NODE_DEBUG_OPTION=--inspect=0.0.0.0:38391
      - RUN_AS_USER=user
      - ENABLE_CHOWN=false
    env_file:
      - env-v1.19/api-gateway.env
      - env-v1.19/global.env
    logging:
      options:
        max-size: 1g



  api:
    image: gcr.io/anyvision-training/api:development
    runtime: runc
    restart: always
    networks:
      anyvision:
        aliases:
          - api.anyvision.local
    ports:
      - "5443:5443"
      - "38389:38389"
    dns: 172.14.0.250                                                        ### internal DNS server address, replace this with external IP of CoreDNS server (A/B config)
    volumes:
      - /storage:/var/www/html
      - /usr/local/share/ca-certificates/anyvision:/usr/local/share/ca-certificates/anyvision
      #- /home/anyvision/Projects/Dash-API:/home/user/Dash-API               ### mount your local project directory to the container
    environment:
      - NODE_DEBUG_OPTION=--inspect=0.0.0.0:38389
      - API_IP=api.anyvision.local
      - MONGO_DB_IP=mongodb.anyvision.local
      - CA_HOST=apigateway.anyvision.local
      - RUN_AS_USER=user
      - ENABLE_CHOWN=false
      - MASS_IMPORT_IP=reid-b.anyvision.local                               ### use this configuration to configure the "b" server reid service in a/b architecture
    env_file:
      - env-v1.19/global.env
      - env-v1.19/api.env
    logging:
      options:
        max-size: 1g



  backend:
    image: gcr.io/anyvision-training/backend:development
    runtime: nvidia
    restart: always
    #command: --disable-services --no-exitkills --debug sleep infinity       ### development mode - disable chaperone init
    networks:
      anyvision:
        aliases:
          - proc-b.anyvision.local
          - reid-b.anyvision.local
          - coll-b.anyvision.local
          - arch-b.anyvision.local
    ports:
      - "4005:4005"
      - "9067:9067"
      - "9068:9068"
      - "9069:9069"
      - "5000-5025:5000-5025/udp"                                            ### for remote VMS rtsp connections
    dns: 172.14.0.250                                                        ### internal DNS server address, replace this with external IP of CoreDNS server (A/B config)
    volumes:
      - /home/user/license:/home/user/license:ro
      - backend_data:/root/pipe_data
      - /storage:/var/www/html
      - /usr/local/share/ca-certificates/anyvision:/usr/local/share/ca-certificates/anyvision
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      #- /root/backend_trunk:/root/backend_trunk                             ### mount your local project directory to the container
    environment:
      - DISPLAY                                                              ### local display mode - do not forget to run "xhost +" as your local host user (not as root)
      - external_ip=proc-b.anyvision.local
      - storage_ip=nginx-b.anyvision.local
      - frame_store_storage_ip=nginx-b.anyvision.local
      - redis_host=127.0.0.1
      - api_service_ip=api.anyvision.local
      - mongodb_host=mongodb.anyvision.local
      - reid_service_ip=reid-b.anyvision.local
      - collate_service_ip=coll-b.anyvision.local
      - track_archive_service_ip=arch-b.anyvision.local
    env_file:
      - env-v1.19/backend.env
      - env-v1.19/global.env
    logging:
      options:
        max-size: 1g
    ipc: host
    devices:
      - "/dev/dri:/dev/dri"
      #- "/dev/video0:/dev/video0"                                           ### USB or built-in camera device


  dashboard:
    image: gcr.io/anyvision-training/dashboard:development
    runtime: nvidia
    restart: always
    #command: --disable-services --no-exitkills --debug sleep infinity       ### development mode - disable chaperone init
    networks:
      - anyvision
    dns: 172.14.0.250                                                        ### internal DNS server address, replace this with external IP of CoreDNS server (A/B config)
    shm_size: 1024M
    volumes:
      - /usr/local/share/ca-certificates/anyvision:/usr/local/share/ca-certificates/anyvision:ro
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      #- /home/anyvision:/home/user/mounted                                  ### mount your home directory to the container
      #- /home/anyvision/Projects/anyvision-dashboard:/home/user/dashboard   ### mount your local project directory to the container
    environment:
      - DISPLAY                                                              ### local display mode - do not forget to run "xhost +" as your local host user (not as root)
      - ssl=true
      - RUN_AS_USER=user
      - ENABLE_CHOWN=false
    env_file:
      - env-v1.19/global.env
    logging:
      options:
        max-size: 1g
    ipc: host
    devices:
      - "/dev/snd:/dev/snd"
      - "/dev/dri:/dev/dri"
