#filename: docker-compose-cloud-gpu.yml
version: '3'


volumes:
  consul_bootstrap_data:
  consul_server_data:
  consul_client_data:

services:


  consul-bootstrap:
    image: consul
    networks:
      - anyvision
    ports:
      # - "8300:8300"
      # - "8400:8400"
      - "8500:8500"
      #- "172.14.0.1:53:8600/udp"
      #- "${HOST_EXTERNAL_IP}:53:8600/udp"
    command:
      - "agent"
      - "-server"
      - "-bootstrap-expect 3"
      - "-ui"
      - "-data-dir=/tmp"
      - "-client=0.0.0.0"
      - "-recursor=8.8.8.8"
      - "-domain=anyvision.local"
    volumes:
      - consul_bootstrap_data:/tmp/consul
    environment:
      - SERVICE_IGNORE=always               ### Ignore this container from Registrator
      - CONSUL_ALLOW_PRIVILEGED_PORTS=
    logging:
      options:
        max-size: 1g
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
        window: 120s



  consul-server:
    image: consul
    networks:
      - anyvision
    command:
      - "agent"
      - "-server"
      - "-retry-join consul-bootstrap"
      - "-ui"
      - "-data-dir=/tmp"
      - "-client=0.0.0.0"
      - "-recursor=8.8.8.8"
      - "-domain=anyvision.local"
    volumes:
      - consul_server_data:/tmp/consul
    environment:
      - SERVICE_IGNORE=always               ### Ignore this container from Registrator
      - CONSUL_ALLOW_PRIVILEGED_PORTS=
    logging:
      options:
        max-size: 1g
    deploy:
      mode: replicated
      replicas: 2
      # placement:
      #   constraints:
      #     - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
        window: 120s



  consul-client:
    image: consul
    networks:
      - anyvision
    command:
      - "agent"
      - "-server"
      - "-retry-join consul-bootstrap"
      - "-ui"
      - "-data-dir=/tmp"
      - "-client=0.0.0.0"
      - "-recursor=8.8.8.8"
      - "-domain=anyvision.local"
    volumes:
      - consul_client_data:/tmp/consul
    environment:
      - SERVICE_IGNORE=always               ### Ignore this container from Registrator
      - CONSUL_ALLOW_PRIVILEGED_PORTS=
    logging:
      options:
        max-size: 1g
    deploy:
      mode: replicated
      replicas: 2
      # placement:
      #   constraints:
      #     - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
        window: 120s



  api-master:
    image: gcr.io/anyvision-training/api-master:development
    runtime: runc
    networks:
      anyvision:
        aliases:
          - api-master.anyvision.local
    #dns: 172.14.0.1  ### internal DNS server address, replace this with external IP of CoreDNS/Consul server (A/B config)
    volumes:
      - /storage:/var/www/html
      - /usr/local/share/ca-certificates/anyvision:/usr/local/share/ca-certificates/anyvision
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - RUN_AS_USER=user
      - ENABLE_CHOWN=false
      #- TZ=Etc/UTC    ## DO NOT CHANGE
    env_file:
      - env/global.env
      - env/api-master.env
    logging:
      options:
        max-size: 1g
    deploy:
      mode: replicated
      replicas: 1
      # placement:
      #   constraints:
      #     - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
        window: 120s
