global:
  scrape_interval: 60s
  evaluation_interval: 60s
  scrape_timeout: 30s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  #external_labels:
  #    monitor: 'docker-host-alpha'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "alert.rules"

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - 'alertmanager:9093'


# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:

  - job_name: 'prometheus'
    static_configs:
      - targets:
          - '127.0.0.1:9090'

  - job_name: 'local_nodeexporter'
    static_configs:
    - targets:
        - 'nodeexporter:9100'
    relabel_configs:
      - source_labels: ['__address__']
        target_label:  instance
        replacement:   127.0.0.1:9100
      - source_labels: ['__address__']
        target_label:  '__address__'
        replacement:   'nodeexporter:9100'


  - job_name: 'local_cadvisor'
    static_configs:
    - targets:
        - 'cadvisor:9101'
    relabel_configs:
      - source_labels: ['__address__']
        target_label:  instance
        replacement:   127.0.0.1:9101
      - source_labels: ['__address__']
        target_label:  '__address__'
        replacement:   'cadvisor:9101'

  # remove the following comments to monitor remote targets

  # - job_name: 'nodeexporter'
  #   file_sd_configs:
  #     - files:
  #       - all_nodes.yml
  #   relabel_configs:
  #     - source_labels: ['__address__']
  #       target_label:  instance
  #       replacement:   ${1}:9100
  #     - source_labels: ['__address__']
  #       target_label:  '__address__'
  #       replacement:   '${1}:9100' # uncomment if nodeexporter is on remote server


  # - job_name: 'cadvisor'
  #   file_sd_configs:
  #     - files:
  #       - all_nodes.yml
  #   relabel_configs:
  #     - source_labels: ['__address__']
  #       target_label:  instance
  #       replacement:   ${1}:9101
  #     - source_labels: ['__address__']
  #       target_label:  '__address__'
  #       replacement:   '${1}:9100' # cadvisor if nodeexporter is on remote server


  - job_name: 'blackbox-url-healthcheck'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    file_sd_configs:
    - files:
      - url_healthcheck.yml
    relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: blackbox:9115  # The blackbox exporter's real hostname:port.
