{
 "title": "monitor all hosts",
 "description": "A simple overview of the most important Docker host and container metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "All Hosts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Server Load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_load1", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Memory Free",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "node_memory_MemFree_bytes", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Available Disk Space left",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_filesystem_free_bytes{fstype=\"ext4\",device!~\".*loop.*\",mountpoint!~\".*docker.*\"}) by (instance,device)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Available Inode Space left",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_fs_inodes_free{device!~\".*loop.*\",device!~\".*overlay.*\",mountpoint!~\".*docker.*\",device!~\".*shm.*\",device!~\".*tmpfs.*\"}) by (instance,device)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk Read/Write bytes ps",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_disk_read_bytes_total) by (instance,device)",
     "legendFormat": "Disk Read {{instance}} {{device}}"
    },
    {
     "expr": "sum(node_disk_written_bytes_total) by (instance,device)",
     "legendFormat": "Disk Write {{instance}} {{device}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode!=\"idle\"}[2m]) * 100) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{device!~\"lo|bond[0-9]|cbr[0-9]|veth.*\"}[2m])) by (instance,interface)",
     "legendFormat": "In {{instance}} {{interface}}"
    },
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{device!~\"lo|bond[0-9]|cbr[0-9]|veth.*\"}[2m])) by (instance,interface)",
     "legendFormat": "Out {{instance}} {{interface}}"
    }
   ]
  }
 ]
}