{
 "title": "system docker monitoring",
 "description": "A simple overview of the most important Docker host and container metrics",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "server", "label": "Server", "query": "label_values(instance)" }
  ]
 },
 "panels": [
  { "title": "Overall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Alerts",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(ALERTS{alertstate=\"firing\"})"
    }
   ]
  },
  {
   "title": "OS Disk",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=~\"$server:.*\",fstype=~\"ext4|xfs\",device!~\".*loop.*\",mountpoint=\"/rootfs\"}"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$server:.*\"}"
    }
   ]
  },
  {
   "title": "CPU load",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(node_load1{instance=~\"$server:.*\",mode!=\"idle\"})"
    }
   ]
  },
  {
   "title": "GPU utilization",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(dcgm_gpu_utilization{instance=~\"$server:.*\"}) * 100"
    }
   ]
  },
  {
   "title": "Disk space",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "min((node_filesystem_size_bytes{fstype=~\"ext4\",instance=~\"$server:.*\"} - node_filesystem_free_bytes{fstype=~\"ext4\",instance=~\"$server:.*\"} )/ node_filesystem_size_bytes{fstype=~\"ext4\",instance=~\"$server:.*\"})"
    }
   ]
  },
  {
   "title": "Memory Load",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes{instance=~\"$server:.*\"} - node_memory_MemAvailable_bytes{instance=~\"$server:.*\"}) / node_memory_MemTotal_bytes{instance=~\"$server:.*\"}) * 100"
    }
   ]
  },
  {
   "title": "Swap",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(node_memory_SwapTotal_bytes{instance=~'$server:.*'} - node_memory_SwapFree_bytes{instance=~'$server:.*'}) / sum(node_memory_SwapTotal_bytes{instance=~'$server:.*'}) * 100"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds{instance=~\"$server:.*\"}"
    }
   ]
  },
  {
   "title": "Data Disk",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=~\"$server:.*\",fstype=~\"ext4|xfs\",device!~\".*loop.*\",mountpoint=\"/rootfs/storage\"}"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(container_tasks_state{name=~\".+\",instance=~\"$server:.*\",state=\"running\"})"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "machine_cpu_cores{instance=~\"$server:.*\"}"
    }
   ]
  },
  { "title": "Host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Server Load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=~\"$server:.*\"} / count by(job, instance)(count by(job, instance, cpu)(node_cpu_seconds_total{instance=~\"$server:.*\"}))",
     "legendFormat": "Load"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_network_transmit_bytes_total{instance=~\"$server:.*\", device!~\"lo|bond[0-9]|cbr[0-9]|veth.*\"}) + sum(node_network_receive_bytes_total{instance=~\"$server:.*\", device!~\"lo|bond[0-9]|cbr[0-9]|veth.*\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "container_network_receive_bytes_total{instance=~\"$server:.*\", device!~\"lo|bond[0-9]|cbr[0-9]|veth.*\"}",
     "legendFormat": "Recive {{interface}}"
    },
    {
     "expr": "container_network_transmit_bytes_total{instance=~\"$server:.*\", device!~\"lo|bond[0-9]|cbr[0-9]|veth.*\"}",
     "legendFormat": "Send {{interface}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{instance=~\"$server:.*\"}) - sum(node_memory_MemFree_bytes{instance=~\"$server:.*\"} + node_memory_Buffers_bytes{instance=~\"$server:.*\"} + node_memory_Cached_bytes{instance=~\"$server:.*\"})",
     "legendFormat": "usage"
    },
    {
     "expr": "sum(node_memory_MemFree_bytes{instance=~\"$server:.*\"})",
     "legendFormat": "free"
    },
    {
     "expr": "sum(node_memory_Shmem_bytes{instance=~\"$server:.*\"})",
     "legendFormat": "shm"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{instance=~\"$server:.*\",mode!=\"idle\"}[2m])) * 100",
     "legendFormat": "Total"
    },
    {
     "expr": "rate(node_cpu_seconds_total{instance=~\"$server:.*\", mode!=\"idle\"}[2m]) * 100",
     "legendFormat": "cpu {{cpu}} , mode {{mode}}"
    }
   ]
  },
  {
   "title": "Used Disk Space",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=~\"$server:.*\",fstype=~\"ext4|xfs\",device!~\".*loop.*\",mountpoint!~\".*docker.*\"} - node_filesystem_free_bytes{instance=~\"$server:.*\",fstype=~\"ext4|xfs\",device!~\".*loop.*\",mountpoint!~\".*docker.*\"}",
     "legendFormat": "Used {{device}}"
    },
    {
     "expr": "node_filesystem_free_bytes{instance=~\"$server:.*\",fstype=~\"ext4|xfs\",device!~\".*loop.*\",mountpoint!~\".*docker.*\"}",
     "legendFormat": "Free {{device}}"
    }
   ]
  },
  {
   "title": "Disk R/W Bps",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 14 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(node_disk_read_bytes_total{instance=~\"$server:.*\"}) + sum(node_disk_written_bytes_total{instance=~\"$server:.*\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(node_disk_read_bytes_total{instance=~\"$server:.*\"}) ",
     "legendFormat": "OUT"
    },
    {
     "expr": "sum(node_disk_written_bytes_total{instance=~\"$server:.*\"})",
     "legendFormat": "IN"
    },
    {
     "expr": "sum(node_disk_read_bytes_total{instance=~\"$server:.*\",device!~\"sr.*\"}) by (device)",
     "legendFormat": "OUT on /{{device}}"
    },
    {
     "expr": "sum(node_disk_written_bytes_total{instance=~\"$server:.*\",device!~\"sr.*\"}) by (device)",
     "legendFormat": "IN on /{{device}}"
    }
   ]
  },
  {
   "title": "Inode Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_fs_inodes_total{instance=~\"$server:.*\",device!~\".*loop.*\",device!~\".*overlay.*\",mountpoint!~\".*docker.*\"} - container_fs_inodes_free{instance=~\"$server:.*\",device!~\".*loop.*\",mountpoint!~\".*docker.*\"}) by (device)",
     "legendFormat": "Usage {{device}}"
    },
    {
     "expr": "sum(container_fs_inodes_total{instance=~\"$server:.*\",device!~\".*loop.*\",device!~\".*overlay.*\",mountpoint!~\".*docker.*\"}) by (device)",
     "legendFormat": "Total {{device}}"
    }
   ]
  },
  {
   "title": "GPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 14 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(dcgm_gpu_utilization{instance=~\"$server:.*\"}) by (gpu)",
     "legendFormat": "utilization gpu {{gpu}}"
    },
    {
     "expr": "sum(dcgm_fb_used{instance=~\"$server:.*\"} * 1024 * 1024  ) by (gpu)",
     "legendFormat": "Memory Usage gpu {{gpu}}"
    },
    {
     "expr": "sum(dcgm_fb_free{instance=~\"$server:.*\"} * 1024  * 1024 ) by (gpu)",
     "legendFormat": "Memory Total gpu {{gpu}}"
    }
   ]
  },
  { "title": "Containers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "CPU Usage per Container",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(container_cpu_usage_seconds_total{name=~\".+\",instance=~\"$server:.*\"}) by (name) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Running Containers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "scalar(count(container_memory_usage_bytes{image!=\"\",instance=~\"$server:.*\"}) > 0)",
     "legendFormat": "containers"
    }
   ]
  },
  {
   "title": "Memory Usage per Container",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_rss{name=~\".+\",instance=~\"$server:.*\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Swap per Container",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_swap{name=~\".+\",instance=~\"$server:.*\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Received Network Traffic per Container",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(container_network_receive_bytes_total{name=~\".+\",instance=~\"$server:.*\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Sent Network Traffic per Container",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(container_network_transmit_bytes_total{name=~\".+\",instance=~\"$server:.*\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Inode Usage per Container",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_fs_inodes_total{instance=~\"$server:.*\",name=~\".+\",device!~\".*loop.*\",device!~\".*overlay.*\",mountpoint!~\".*docker.*\"} - container_fs_inodes_free{instance=~\"$server:.*\",device!~\".*loop.*\",mountpoint!~\".*docker.*\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "RW per Container",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_fs_writes_total{instance=~\"$server:.*\",name=~\".+\",device!~\".*loop.*\",device!~\".*overlay.*\",mountpoint!~\".*docker.*\"}) by (name)",
     "legendFormat": "Write {{name}}"
    },
    {
     "expr": "sum(container_fs_reads_total{instance=~\"$server:.*\",name=~\".+\",device!~\".*loop.*\",device!~\".*overlay.*\",mountpoint!~\".*docker.*\"}) by (name)",
     "legendFormat": "Read {{name}}"
    }
   ]
  }
 ]
}