---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: backend-deployment
spec:
  selector:
    matchLabels:
      app: ui-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: ui-deployment
    spec:
      hostname: backend
      hostAliases:
        - ip: "127.0.0.1"
          hostnames:
          - "proc-localnode.anyvision.local"
          - "reid-localnode.anyvision.local"
          - "coll-localnode.anyvision.local"
          - "arch-localnode.anyvision.local"
      restartPolicy: Always
      containers:
      - name: backend
        image: gcr.io/anyvision-production/backend-pyconcrete:1.19.4
        ports:
        - containerPort: 27017
        volumeMounts:
        - mountPath: "/home/user/license"
          name: licenseex
        - mountPath: "/root/pipe_data"
          name: pipedata
        - mountPath: "/var/www/html"
          name: html
        - mountPath: "/dev/shm"
          name: shm
        - mountPath: "/tmp/.X11-unix"
          name: x11
        - name: secret-volume
          mountPath: "/usr/local/share/ca-certificates/anyvision"
          readOnly: true
        - name: tz-config
          mountPath: /etc/localtime
        env:
        - name: paths_pipe_uuid_file_path
          value: "/root/pipe_data/pipe_id"
        - name: paths_custom_ip_settings_path
          value: "/root/pipe_data/custom_ip_settings_file.json"
        - name: api_service_ip
          value: "ui-deployment.default.svc.cluster.local"
        - name: DASHBOARD_XPRA_HOST
          value: "dashboard"
        - name: DASHBOARD_XPRA_PORT
          value: "20000"
        - name: BACKEND_XPRA_HOST
          value: "backend"
        - name: BACKEND_XPRA_PORT
          value: "10000"
        - name: LINES
          value: "40"
        - name: COLUMNS
          value: "160"
        - name: RABBITMQ_DEFAULT_USER
          value: "user"
        - name: RABBITMQ_DEFAULT_PASS
          value: "password"
        - name: ENABLE_DOCKERIZE
          value: "true"
        - name: ENABLE_MKDIR
          value: "true"
        - name: ENABLE_CONFD_TEAMPLATER
          value: "true"
        - name: ENABLE_CONFD
          value: "true"
        - name: ENABLE_WATCHER
          value: "true"
        - name: ENABLE_BUFFER_CLEANER
          value: "true"
        - name: ENABLE_FRAMESTORE_CLEANER
          value: "true"
        - name: ENABLE_PROCESS_SERVICE
          value: "true"
        - name: ENABLE_REID_SERVICE
          value: "true"
        - name: ENABLE_TRACK_ARCHIVE_SERVICE
          value: "true"
        - name: ENABLE_COLLATE_SERVICE
          value: "true"
        - name: ENABLE_REDIS_SERVICE
          value: "true"
        - name: ENABLE_XPRA_SERVICE
          value: "false"
        - name: ENABLE_CRON_PIPE_IMG_TEMPORARY
          value: "false"
        - name: ENABLE_CRON_MASS_IMPORT_REPORTS
          value: "true"
        - name: ENABLE_DOCKER_STDOUT
          value: "true"
        - name: ENABLE_DOCKER_LOG
          value: "false"
        - name: flask_port
          value: "4005"
        - name: api_service_port
          value: "5443"
        - name: reid_service_port
          value: "9069"
        - name: collate_service_port
          value: "9067"
        - name: track_archive_service_port
          value: "9068"
        - name: redis_port
          value: "6379"
        - name: mongodb_port
          value: "27017"
        - name: REQUESTS_CA_BUNDLE
          value: "/usr/local/share/ca-certificates/anyvision/ca.crt"
        - name: misc_ssl_certificate_path
          value: "/usr/local/share/ca-certificates/anyvision/server.crt"
        - name: misc_ssl_key_path
          value: "/usr/local/share/ca-certificates/anyvision/server.key"
        - name: REID_DATA_SERVICE_GPU
          value: "0"
        - name: AGE_EXTRACTION_GPU
          value: "0"
        - name: xvfb_screen_resolution
          value: "1920x1080x24"
        - name: DISPLAY
          value: ":0"
        - name: NVIDIA_VISIBLE_DEVICES
          value: "all"
        - name: NVIDIA_DRIVER_CAPABILITIES
          value: "all"
        - name: log_level
          value: "DEBUG"
        - name: logs_backup_files
          value: "1"
        - name: logs_max_size
          value: "20"
        - name: GLOG_minloglevel
          value: "2"
        - name: DISPLAY
          value: ":0"
        - name: external_ip
          value: "proc-localnode.anyvision.local"
        - name: storage_ip
          value: "nginx-localnode.anyvision.local"
        - name: frame_store_storage_ip
          value: "nginx-localnode.anyvision.local"
        - name: redis_host
          value: "127.0.0.1"
        - name: api_service_il
          value: "api-localnode.anyvision.local"
        - name: mongodb_host
          value: "ui-deployment.default.svc.cluster.local"
        - name: reid_service_ip
          value: "reid-localnode.anyvision.local"
        - name: collate_service_ip
          value: "coll-localnode.anyvision.local"
        - name: track_archive_service_ip
          value: "arch.localnode.anyvision.local"
      - name: nginx
        image: gcr.io/anyvision-training/nginx-rtmp:ssl
        ports:
        - containerPort: 1935
        - containerPort: 443
        - containerPort: 80
        volumeMounts:
        - mountPath: "/opt/nginx/html"
          name: html
        - name: secret-volume
          mountPath: "/usr/local/share/ca-certificates/anyvision"
          readOnly: true
        - name: tz-config
          mountPath: /etc/localtime
        env:
        - name: CERT_KEY
          value: "/usr/local/share/ca-certificates/anyvision/server.key"
        - name: CERT_FILE
          value: "/usr/local/share/ca-certificates/anyvision/server.crt"
        - name: CERT_PASS_FILE
          value: "/usr/local/share/ca-certificates/anyvision/pass"
        - name: DASHBOARD_XPRA_HOST
          value: "dashboard"
        - name: DASHBOARD_XPRA_PORT
          value: "20000"
        - name: BACKEND_XPRA_HOST
          value: "backend"
        - name: BACKEND_XPRA_PORT
          value: "10000"
        - name: LINES
          value: "40"
        - name: COLUMNS
          value: "160"
        - name: RABBITMQ_DEFAULT_USER
          value: "user"
        - name: RABBITMQ_DEFAULT_PASS
          value: "password"
        - name: limit_rate_speed
          value: "0"
      volumes:
      - name: licenseex
        persistentVolumeClaim:
          claimName: license-claim
      - name: pipedata
        persistentVolumeClaim:
          claimName: pipedata-claim
      - name: html
        persistentVolumeClaim:
          claimName: html-claim1
      - name: shm
        persistentVolumeClaim:
          claimName: shm-claim
      - name: x11
        persistentVolumeClaim:
          claimName: x11-claim
      - name: secret-volume
        secret:
          secretName: secretname
      - name: tz-config
        hostPath:
           path: /etc/localtime
---
apiVersion: v1
kind: Service
metadata:
  name: backend-deployment
spec:
  clusterIP: None
  ports:
  - name: "http"
    port: 80
    targetPort: 80
    protocol: TCP
  - name: "https"
    port: 443
    targetPort: 443
    protocol: TCP
  - name: "1935"
    port: 1935
    targetPort: 1935
    protocol: TCP
  selector:
    app: ui-deployment
