---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: backend-deployment
spec:
  selector:
    matchLabels:
      app: ui-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: ui-deployment
    spec:
      hostname: backend-deployment
      dnsConfig:
        nameservers:
          - 1.2.3.4
        searches:
          - anyvision.local
      hostAliases:
        - ip: "127.0.0.1"
          hostnames:
          - "proc-localnode.anyvision.local"
          - "reid-localnode.anyvision.local"
          - "coll-localnode.anyvision.local"
          - "arch-localnode.anyvision.local"
      restartPolicy: Always
      containers:
      - name: backend
        image: gcr.io/anyvision-production/backend-pyconcrete:1.19.4
        ports:
        - containerPort: 27017
        volumeMounts:
        - mountPath: "/home/user/license"
          name: licenseex
        - mountPath: "/root/pipedata"
          name: pipedata
        - mountPath: "/var/www/html"
          name: html
        - mountPath: "/dev/shm"
          name: shm
        - mountPath: "/tmp/.X11-unix"
          name: x11
        - name: secret-volume
          mountPath: "/usr/local/share/ca-certificates/anyvision"
          readOnly: true
        env:
        - name: DASHBOARD_XPRA_HOST
          value: "dashboard"
        - name: DASHBOARD_XPRA_PORT
          value: "20000"
        - name: BACKEND_XPRA_HOST
          value: "backend"
        - name: BACKEND_XPRA_PORT
          value: "10000"
        - name: LINES
          value: "40"
        - name: COLUMNS
          value: "160"
        - name: RABBITMQ_DEFAULT_USER
          value: "user"
        - name: RABBITMQ_DEFAULT_PASS
          value: "password"
        - name: ENABLE_DOCKERIZE
          value: "true"
        - name: ENABLE_MKDIR
          value: "true"
        - name: ENABLE_CONFD_TEAMPLATER
          value: "true"
        - name: ENABLE_CONFD
          value: "true"
        - name: ENABLE_WATCHER
          value: "true"
        - name: ENABLE_BUFFER_CLEANER
          value: "true"
        - name: ENABLE_FRAMESTORE_CLEANER
          value: "true"
        - name: ENABLE_PROCESS_SERVICE
          value: "true"
        - name: ENABLE_REID_SERVICE
          value: "true"
        - name: ENABLE_TRACK_ARCHIVE_SERVICE
          value: "true"
        - name: ENABLE_COLLATE_SERVICE
          value: "true"
        - name: ENABLE_REDIS_SERVICE
          value: "true"
        - name: ENABLE_XPRA_SERVICE
          value: "false"
        - name: ENABLE_CRON_PIPE_IMG_TEMPORARY
          value: "false"
        - name: ENABLE_CRON_MASS_IMPORT_REPORTS
          value: "true"
        - name: ENABLE_DOCKER_STDOUT
          value: "true"
        - name: ENABLE_DOCKER_LOG
          value: "false"
        - name: flask_port
          value: "4005"
        - name: api_service_port
          value: "5443"
        - name: reid_service_port
          value: "9069"
        - name: collate_service_port
          value: "9067"
        - name: track_archive_service_port
          value: "9068"
        - name: redis_port
          value: "6379"
        - name: mongodb_port
          value: "27017"
        - name: REQUESTS_CA_BUNDLE
          value: "/usr/local/share/ca-certificates/anyvision/anyvisionCA.pem"
        - name: REID_DATA_SERVICE_GPU
          value: "0"
        - name: AGE_EXTRACTION_GPU
          value: "0"
        - name: xvfb_screen_resolution
          value: "1920x1080x24"
        - name: DISPLAY
          value: ":0"
        - name: NVIDIA_VISIBLE_DEVICES
          value: "all"
        - name: NVIDIA_DRIVER_CAPABILITIES
          value: "all"
        - name: log_level
          value: "DEBUG"
        - name: logs_backup_files
          value: "1"
        - name: logs_max_size
          value: "20"
        - name: GLOG_minloglevel
          value: "2"
        - name: DISPLAY
          value: ":0"
        - name: external_ip
          value: "proc-localnode.anyvision.local"
        - name: storage_ip
          value: "nginx-localnode.anyvision.local"
        - name: frame_store_storage_ip
          value: "nginx-localnode.anyvision.local"
        - name: redis_host
          value: "127.0.0.1"
        - name: api_service_il
          value: "api-localnode.anyvision.local"
        - name: mongodb_host
          value: "ui-deployment.default.svc.cluster.local"
        - name: reid_service_ip
          value: "reid-localnode.anyvision.local"
        - name: collate_service_ip
          value: "coll-localnode.anyvision.local"
        - name: track_archive_service_ip
          value: "arch.localnode.anyvision.local"
      volumes:
      - name: licenseex
        persistentVolumeClaim:
          claimName: license-claim
      - name: pipedata
        persistentVolumeClaim:
          claimName: pipedata-claim
      - name: html
        persistentVolumeClaim:
          claimName: html-claim1
      - name: shm
        persistentVolumeClaim:
          claimName: shm-claim
      - name: x11
        persistentVolumeClaim:
          claimName: x11-claim
      - name: secret-volume
        secret:
          secretName: secretname
          items:
          - key: apigateway.anyvision.local.crt
            path: tls
          - key: apigateway.anyvision.local.key.pem
            path: tls
          - key: anyvisionCA.pem
            path: tls
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: license-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pipedata-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: html-claim1
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: shm-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: x11-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: task-pv-volume3
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/storage3"
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: task-pv-volume4
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/storage4"
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: task-pv-volume5
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/storage5"
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: task-pv-volume6
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/storage6"
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: task-pv-volume7
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/storage7"
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: task-pv-volume8
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/storage8"
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: task-pv-volume9
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/storage9"
