---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: bro-deployment
spec:
  selector:
    matchLabels:
      app: ui-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: ui-deployment
    spec:
      hostname: broadcaster
      restartPolicy: Always
      containers:
      - name: broadcaster
        image: gcr.io/anyvision-training/broadcaster:development
        env:
        - name: DASHBOARD_XPRA_HOST
          value: "dashboard"
        - name: DASHBOARD_XPRA_PORT
          value: "20000"
        - name: BACKEND_XPRA_HOST
          value: "backend"
        - name: BACKEND_XPRA_PORT
          value: "10000"
        - name: LINES
          value: "40"
        - name: COLUMNS
          value: "160"
        - name: RABBITMQ_DEFAULT_USER
          value: "user"
        - name: RABBITMQ_DEFAULT_PASS
          value: "password"
        - name: NODE_DEBUG_OPTION
          value: "--inspect=0.0.0.0:38391"
        - name: api_service_ipc
          value: "ui-deployment.default.svc.cluster.local"
        - name: BCAST_SOCKETIO_API_URL
          value: "https://ui-deployment.default.svc.cluster.local:5443"
        - name: RUN_AS_USER
          value: "user"
        - name: ENABLE_CHOWN
          value: "true"
        - name: ENABLE_DOCKER_STDOUT
          value: "true"
        - name: ENABLE_DOCKER_LOG
          value: "false"
        - name: CA_PATH
          value: "/usr/local/share/ca-certificates/anyvision/anyvisionCA.pem"
        - name: BCAST_RMQ_ONLY_SUBJECTS
          value: "true"
        volumeMounts:
        - name: tz-config
          mountPath: /etc/localtime
        - name: secret-volume
          mountPath: "/usr/local/share/ca-certificates/anyvision"
          readOnly: true
      - name: rabbitmq
        image: gcr.io/anyvision-training/rabbitmq:latest
        ports:
        - containerPort: 5671 
        - containerPort: 5672
        - containerPort: 15672
        - containerPort: 15671
        env:
        - name: DASHBOARD_XPRA_HOST
          value: "dashboard"
        - name: DASHBOARD_XPRA_PORT
          value: "20000"
        - name: BACKEND_XPRA_HOST
          value: "backend"
        - name: BACKEND_XPRA_PORT
          value: "10000"
        - name: LINES
          value: "40"
        - name: COLUMNS
          value: "160"
        - name: RABBITMQ_DEFAULT_USER
          value: "user"
        - name: RABBITMQ_DEFAULT_PASS
          value: "password"
        volumeMounts:
        - name: tz-config
          mountPath: /etc/localtime
        - name: secret-volume
          mountPath: "/usr/local/share/ca-certificates/anyvision"
          readOnly: true
        - name: rabbitmq
          mountPath: "/var/lib/rabbitmq"
      volumes:
      - name: secret-volume
        secret:
          secretName: secretname
          items:
          - key: apigateway.anyvision.local.crt
            path: tls
          - key: apigateway.anyvision.local.key.pem
            path: tls
          - key: anyvisionCA.pem
            path: tls
          - key: apigateway.anyvision.local.full.pem
            path: tls
      - name: tz-config
        hostPath:
           path: /etc/localtime
      - name: rabbirmq
        persistentVolumeClaim:
          claimName: rabbitmq-claim
---
apiVersion: v1
kind: Service
metadata:
  name: broadcaster-deployment
spec:
  type: LoadBalancer
  ports:
  - name: "5671"
    port: 5671
    targetPort: 5671
    protocol: TCP
  - name: "5672"
    port: 5672
    targetPort: 5672
    protocol: TCP
  - name: "15671"
    port: 15671
    targetPort: 15671
    protocol: TCP
  - name: "15672"
    port: 15672
    targetPort: 15672
    protocol: TCP
  selector:
    app: ui-deployment
