---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: cron-deployment
spec:
  selector:
    matchLabels:
      app: ui-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: ui-deployment
    spec:
      hostname: cron
      restartPolicy: Always
      containers:
      - name: cron
        image: gcr.io/anyvision-production/supercronic:latest
        env:
        - name: TO_DATE_TRACK_DELETE
          value: "30"
        - name: DASHBOARD_XPRA_HOST
          value: "dashboard"
        - name: DASHBOARD_XPRA_PORT
          value: "20000"
        - name: BACKEND_XPRA_HOST
          value: "backend"
        - name: BACKEND_XPRA_PORT
          value: "10000"
        - name: LINES
          value: "40"
        - name: COLUMNS
          value: "160"
        - name: RABBITMQ_DEFAULT_USER
          value: "user"
        - name: RABBITMQ_DEFAULT_PASS
          value: "password"
        volumeMounts:
        - mountPath: "/var/www/html"
          name: html
        - name: tz-config
          mountPath: "/etc/localtime"
        - name: crontab
          mountPath: "/etc/crontab"
      volumes:
      - name: html
        persistentVolumeClaim:
          claimName: html-claim
      - name: tz-config
        hostPath:
           path: /etc/localtime
      - name: crontab
        hostPath:
           path: /var/crontab
