---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: apigateway-deployment
spec:
  selector:
    matchLabels:
      app: ui-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: ui-deployment
        run: apig
    spec:
      hostname: apigateway
      restartPolicy: Always
      containers:
      - name: apigateway
        image: gcr.io/anyvision-production/api-gateway:1.19.4
        ports:
        - containerPort: 9443
        env:
        - name: DASHBOARD_XPRA_HOST
          value: "dashboard"
        - name: DASHBOARD_XPRA_PORT
          value: "20000"
        - name: BACKEND_XPRA_HOST
          value: "backend"
        - name: BACKEND_XPRA_PORT
          value: "10000"
        - name: LINES
          value: "40"
        - name: COLUMNS
          value: "160"
        - name: RABBITMQ_DEFAULT_USER
          value: "user"
        - name: RABBITMQ_DEFAULT_PASS
          value: "password"
        - name:  GATEWAY_PORT
          value: "8080"
        - name: GATEWAY_SECURE_PORT
          value: "9443"
        - name: GATEWAY_HOST
          value: "apigateway.default.svc.cluster.local"
        - name: TLS_DOMAIN
          value: "*.default.svc.cluster.local"
        - name: TLS_PEM_PATH
          value: "/usr/local/share/ca-certificates/anyvision/server.key"
        - name: TLS_CRT_PATH
          value: "/usr/local/share/ca-certificates/anyvision/server.crt"
        - name: CA_PATH
          value: "/usr/local/share/ca-certificates/anyvision/ca.crt"
        - name: API_PORT
          value: "5443"
        - name: API_HOST
          value: "ui-deployment.default.svc.cluster.local"
        - name: DASH_API_URL
          value: "http://ui-deployment.default.svc.cluster.local:5443"
        - name: GATEWAY_SECURE_URL
          value: "https://ui-deployment.default.svc.cluster.local:9443"
        - name: GATEWAY_URL
          value: "http://apigateway.default.svc.cluster.local:9443"
        - name: JWT_API_PUBKEY_PATH
          value: "config/keys/bettertomorrowJwtSecret.pem"
        - name: API_JWT_SECRET
          value: "thehouseisonfire"
        - name: IS_FORCE_JWT_SECRET_CHANGE
          value: "false"
        - name: CA_FULL_CHAIN_CERTS
          value: "/usr/local/share/ca-certificates/anyvision/server.crt"
        - name: REDIS_HOST
          value: "apigateway.default.svc.cluster.local"
        - name: ENABLE_DOCKER_STDOUT
          value: "true"
        - name: ENABLE_DOCKER_LOG
          value: "true"
        - name: RUN_AS_USER
          value: "user"
        - name: ENABLE_CHOWN
          value: "false"
        - name: ENABLE_CREATE_SSL
          value: "false"
        volumeMounts:
        - mountPath: "/var/www/html"
          name: html
        - name: tz-config
          mountPath: /etc/localtime
        - name: secret-volume
          mountPath: "/usr/local/share/ca-certificates/anyvision"
          readOnly: true
      - name: redis
        image: gcr.io/anyvision-production/redis:latest
        volumeMounts:
        - mountPath: "/data"
          name: redis-db-data
        - name: tz-config
          mountPath: /etc/localtime
      volumes:
      - name: html
        persistentVolumeClaim:
          claimName: html-claim
      - name: redis-db-data
        persistentVolumeClaim:
          claimName: redis-db-data-claim
      - name: secret-volume
        secret:
          secretName: secretname
      - name: tz-config
        hostPath:
           path: /etc/localtime
---
apiVersion: v1
kind: Service
metadata:
  name: apigateway
spec:
  clusterIP: None
  ports:
  - name: "apigateway"
    port: 9443
    targetPort: 9443
    protocol: TCP
  selector:
    run: apig
---
apiVersion: v1
kind: Service
metadata:
  name: apig-lb
spec:
  externalIPs:
  - 10.132.0.35
  type: LoadBalancer
  ports:
   - name: http-apig
     port: 9443
     targetPort: 9443
  selector:
    run: apig
