version: '3.3'

volumes:
  mongo_db_data:
  redis_db_data:
  backend_data:
  api_gateway_keys:


### Steps:
### 1) Create an Overlay network on the Swarm Master (one time) using:
### docker network create --driver=overlay --attachable prod
###
### 2) Join the Overlay network with a temp container (required because of bug https://github.com/docker/compose/issues/4601):
### docker run -d --rm --name nginx_prod_join --network prod nginx
###
### Run this compose up:
### docker-compose -f ... up -d
###
### Remove the temp container:
### docker stop nginx_prod_join


networks:
  prod:
    external: true


services:


#  registrator:
#    image: gliderlabs/registrator
#    command: ["consul://consul-bootstrap:8500"]
#    networks:
#      - prod
#    volumes:
#      - /var/run/docker.sock:/tmp/docker.sock
#    logging:
#      options:
#        max-size: 1g
#    deploy:
#      mode: replicated
#      replicas: 1
#      placement:
#        constraints:
#          - node.labels.site==luxor
#      restart_policy:
#        condition: on-failure
#        delay: 5s
#        max_attempts: 10
#        window: 120s



  guacamole:
    image: gcr.io/anyvision-training/guacamole:0.9.14
    restart: always
    networks:
      - prod
    ports:
      - "8080:8080"
    volumes:
      - ./guacamole/user-mapping-cloud.xml:/etc/guacamole/user-mapping.xml
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    env_file:
      - env/global.env
    logging:
      options:
        max-size: 1g



  sftp:
    image: atmoz/sftp
    restart: always
    networks:
      prod:
        aliases:
          - sftp-luxor.anyvision.local
    volumes:
      - /storage/sftp_data:/home/user
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    command: user:pass:2000:2000:files
    env_file:
      - env/global.env
    logging:
      options:
        max-size: 1g



  nginx:
    image: gcr.io/anyvision-training/nginx-rtmp:ssl
    restart: always
    networks:
      prod:
        aliases:
          - nginx-luxor.anyvision.local
    ports:
      - "1935:1935"
      #- "443:443"
      #- "80:80"
    volumes:
      - /storage:/opt/nginx/html:ro
      - /usr/local/share/ca-certificates/anyvision:/usr/local/share/ca-certificates/anyvision
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    env_file:
      - env/global.env
    logging:
      options:
        max-size: 1g



  desktop:
    image: gcr.io/anyvision-training/desktop
    restart: always
    privileged: true   ## FOR ACCESSING DEVICES - NOT HOT-PLUGGABLE
    networks:
      prod:
        aliases:
          - desktop-luxor.anyvision.local
    volumes:
      - /storage/sftp_data:/sftp:ro
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - DISPLAY=:0
      - VNC_PASSWORD=123456
    env_file:
      - env/global.env
    ipc: host
    logging:
      options:
        max-size: 1g



  cron:
    image: gcr.io/anyvision-training/supercronic:latest
    restart: always
    networks:
      prod:
        aliases:
          - cron-luxor.anyvision.local
    volumes:
      - /storage:/var/www/html
      - ./env/crontab:/etc/crontab
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - TO_DATE_TRACK_DELETE=30
    logging:
      options:
        max-size: 1g



  rabbitmq:
    image: gcr.io/anyvision-training/rabbitmq:latest
    restart: always
    networks:
      prod:
        aliases:
          - rabbitmq-luxor.anyvision.local
    #ports:
      #- "5761:5761"
      #- "15761:15761"
    volumes:
      - /storage/rabbitmq:/var/lib/rabbitmq
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    env_file:
      - env/global.env
    logging:
      options:
        max-size: 1g



  redis:
    image: gcr.io/anyvision-training/redis:latest
    restart: always
    networks:
      prod:
        aliases:
          - redis-luxor.anyvision.local
    sysctls:
      - net.core.somaxconn=511
    volumes:
      - redis_db_data:/data:rw
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    logging:
      options:
        max-size: 1g



  broadcaster:
    image: gcr.io/anyvision-training/broadcaster:1.19.2
    restart: always
    hostname: broadcaster
    networks:
      prod:
        aliases:
          - broadcaster-luxor.anyvision.local
    volumes:
      - /usr/local/share/ca-certificates/anyvision:/usr/local/share/ca-certificates/anyvision
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    depends_on:
      - api
    environment:
      - RUN_AS_USER=user
      - ENABLE_CHOWN=false
    env_file:
      - env/global.env
      - env/broadcaster.env
    logging:
      options:
        max-size: 1g



  apigateway:
    image: gcr.io/anyvision-training/api-gateway:1.19.2
    restart: always
    networks:
      prod:
        aliases:
          - apigateway-luxor.anyvision.local
    ports:
      - "9443:9443"
    volumes:
      - /storage:/var/www/html
      - api_gateway_keys:/home/user/api-gateway/config/keys
      - /usr/local/share/ca-certificates/anyvision:/usr/local/share/ca-certificates/anyvision
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    depends_on:
      - redis
    environment:
      - RUN_AS_USER=user
      - ENABLE_CHOWN=false
    env_file:
      - env/api-gateway.env
      - env/global.env
    logging:
      options:
        max-size: 1g



  mongodb:
    image: gcr.io/anyvision-training/mongo:3.6-jessie
    networks:
      prod:
        aliases:
          - mongodb-luxor.anyvision.local
    #ports:
      #- "27017:27017"
    volumes:
      - mongo_db_data:/data/db
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    env_file:
      - env/global.env
    logging:
      options:
        max-size: 1g



  api:
    image: gcr.io/anyvision-training/api:1.19.2
    restart: always
    networks:
      prod:
        aliases:
          - api-luxor.anyvision.local
    ports:
      - "5443:5443"
    volumes:
      - /storage:/var/www/html
      - /usr/local/share/ca-certificates/anyvision:/usr/local/share/ca-certificates/anyvision
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - API_IP=api-luxor.anyvision.local
      - MONGO_DB_IP=mongodb-luxor.anyvision.local
      - CA_HOST=apigateway-luxor.anyvision.local
      - MASS_IMPORT_IP=reid-luxor.anyvision.local
      - RUN_AS_USER=user
      - ENABLE_CHOWN=false
    env_file:
      - env/global.env
      - env/api.env
    logging:
      options:
        max-size: 1g



  backend:
    image: gcr.io/anyvision-training/backend-pyconcrete:1.19.2
    restart: always
    privileged: true   ## FOR ACCESSING DEVICES - NOT HOT-PLUGGABLE
    networks:
      prod:
        aliases:
          - proc-luxor.anyvision.local
          - reid-luxor.anyvision.local
          - coll-luxor.anyvision.local
          - arch-luxor.anyvision.local
    ports:
      #- "4005:4005"
      #- "9067:9067"
      #- "9068:9068"
      #- "9069:9069"
      - "5000-5025:5000-5025/udp"                                            ### for remote VMS rtsp connections
    volumes:
      - /home/user/license:/home/user/license:ro
      - backend_data:/root/pipe_data
      - /storage:/var/www/html
      - /usr/local/share/ca-certificates/anyvision:/usr/local/share/ca-certificates/anyvision
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - DISPLAY=:0
      - external_ip=proc-luxor.anyvision.local
      - storage_ip=nginx-luxor.anyvision.local
      - frame_store_storage_ip=nginx-luxor.anyvision.local
      - redis_host=127.0.0.1
      - api_service_ip=api-luxor.anyvision.local
      - mongodb_host=mongodb-luxor.anyvision.local
      - reid_service_ip=reid-luxor.anyvision.local
      - collate_service_ip=coll-luxor.anyvision.local
      - track_archive_service_ip=arch-luxor.anyvision.local
    env_file:
      - env/backend.env
      - env/global.env
    logging:
      options:
        max-size: 1g
    ipc: host



  dashboard:
    image: gcr.io/anyvision-training/dashboard:1.19.2
    restart: always
    privileged: true   ## FOR ACCESSING DEVICES - NOT HOT-PLUGGABLE
    networks:
      - prod
    shm_size: 1024M
    volumes:
      - /storage/sftp_data:/sftp:rw
      - /usr/local/share/ca-certificates/anyvision:/usr/local/share/ca-certificates/anyvision:ro
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /media:/home/user/media:ro
      - /storage/share:/home/user/share:rw
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - DISPLAY=:0
      - ssl=true
      - RUN_AS_USER=user
      - ENABLE_CHOWN=false
    env_file:
      - env/global.env
      - env/api-gateway.env
      - env/dashboard.env
    logging:
      options:
        max-size: 1g
    ipc: host