# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: track.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
import common_pb2 as common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='track.proto',
  package='anyvision.protos',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0btrack.proto\x12\x10\x61nyvision.protos\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x0c\x63ommon.proto\"\xf2\x03\n\x05Track\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\tsource_id\x18\x02 \x01(\t\x12\x0f\n\x07site_id\x18\x03 \x01(\t\x12\x17\n\x0f\x63\x61mera_group_id\x18\x04 \x01(\t\x12\x1b\n\x13\x66rame_store_session\x18\x05 \x01(\t\x12$\n\x04type\x18\x06 \x01(\x0e\x32\x16.anyvision.protos.Type\x12\x36\n\x12\x63reation_timestamp\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x14\n\x08\x66\x65\x61tures\x18\x08 \x03(\x02\x42\x02\x10\x01\x12\x12\n\nfe_quality\x18\t \x01(\x02\x12/\n\ndetections\x18\n \x03(\x0b\x32\x1b.anyvision.protos.Detection\x12\x13\n\x0bzoom_in_img\x18\x0b \x03(\t\x12\x14\n\x0czoom_out_img\x18\x0c \x03(\t\x12\x12\n\ncollate_id\x18\r \x01(\t\x12.\n\rclose_matches\x18\x0e \x03(\x0b\x32\x17.anyvision.protos.Match\x12.\n\x06gender\x18\x0f \x01(\x0e\x32\x1e.anyvision.protos.Track.Gender\"+\n\x06Gender\x12\r\n\tUNDEFINED\x10\x00\x12\x07\n\x03MEN\x10\x01\x12\t\n\x05WOMEN\x10\x02\"v\n\tDetection\x12\x16\n\x0e\x64\x65tector_score\x18\x01 \x01(\x02\x12\x14\n\x0c\x66rame_number\x18\x02 \x01(\x03\x12\x11\n\tframe_pts\x18\x03 \x01(\x03\x12(\n\x08position\x18\x04 \x01(\x0b\x32\x16.anyvision.protos.Rectb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,common__pb2.DESCRIPTOR,])



_TRACK_GENDER = _descriptor.EnumDescriptor(
  name='Gender',
  full_name='anyvision.protos.Track.Gender',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNDEFINED', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MEN', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WOMEN', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=536,
  serialized_end=579,
)
_sym_db.RegisterEnumDescriptor(_TRACK_GENDER)


_TRACK = _descriptor.Descriptor(
  name='Track',
  full_name='anyvision.protos.Track',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='anyvision.protos.Track.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='source_id', full_name='anyvision.protos.Track.source_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='site_id', full_name='anyvision.protos.Track.site_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='camera_group_id', full_name='anyvision.protos.Track.camera_group_id', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='frame_store_session', full_name='anyvision.protos.Track.frame_store_session', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='anyvision.protos.Track.type', index=5,
      number=6, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='creation_timestamp', full_name='anyvision.protos.Track.creation_timestamp', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='features', full_name='anyvision.protos.Track.features', index=7,
      number=8, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\020\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fe_quality', full_name='anyvision.protos.Track.fe_quality', index=8,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='detections', full_name='anyvision.protos.Track.detections', index=9,
      number=10, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='zoom_in_img', full_name='anyvision.protos.Track.zoom_in_img', index=10,
      number=11, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='zoom_out_img', full_name='anyvision.protos.Track.zoom_out_img', index=11,
      number=12, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='collate_id', full_name='anyvision.protos.Track.collate_id', index=12,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='close_matches', full_name='anyvision.protos.Track.close_matches', index=13,
      number=14, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gender', full_name='anyvision.protos.Track.gender', index=14,
      number=15, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _TRACK_GENDER,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=579,
)


_DETECTION = _descriptor.Descriptor(
  name='Detection',
  full_name='anyvision.protos.Detection',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='detector_score', full_name='anyvision.protos.Detection.detector_score', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='frame_number', full_name='anyvision.protos.Detection.frame_number', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='frame_pts', full_name='anyvision.protos.Detection.frame_pts', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='position', full_name='anyvision.protos.Detection.position', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=581,
  serialized_end=699,
)

_TRACK.fields_by_name['type'].enum_type = common__pb2._TYPE
_TRACK.fields_by_name['creation_timestamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_TRACK.fields_by_name['detections'].message_type = _DETECTION
_TRACK.fields_by_name['close_matches'].message_type = common__pb2._MATCH
_TRACK.fields_by_name['gender'].enum_type = _TRACK_GENDER
_TRACK_GENDER.containing_type = _TRACK
_DETECTION.fields_by_name['position'].message_type = common__pb2._RECT
DESCRIPTOR.message_types_by_name['Track'] = _TRACK
DESCRIPTOR.message_types_by_name['Detection'] = _DETECTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Track = _reflection.GeneratedProtocolMessageType('Track', (_message.Message,), dict(
  DESCRIPTOR = _TRACK,
  __module__ = 'track_pb2'
  # @@protoc_insertion_point(class_scope:anyvision.protos.Track)
  ))
_sym_db.RegisterMessage(Track)

Detection = _reflection.GeneratedProtocolMessageType('Detection', (_message.Message,), dict(
  DESCRIPTOR = _DETECTION,
  __module__ = 'track_pb2'
  # @@protoc_insertion_point(class_scope:anyvision.protos.Detection)
  ))
_sym_db.RegisterMessage(Detection)


_TRACK.fields_by_name['features']._options = None
# @@protoc_insertion_point(module_scope)
