setup.kibana:

  # Kibana Host
  # Scheme and port can be left out and will be set to the default (http and 5601)
  # In case you specify and additional path, the scheme is required: http://localhost:5601/path
  # IPv6 addresses should always be defined as: https://[2001:db8::1]:5601
  host: "kibana:5601"

#----------------------------- Logstash output --------------------------------
filebeat:
  prospectors:

  - type: log
    input_type: log
    enabled: true
    fields:
      type: pipe-logs
    fields_under_root: true
    paths:
    - /var/storage/pipe-logs/*/*.log
    exclude_files: [".gz"]
    ignore_older: 24h
    encoding: utf-8

  - type: log
    input_type: log
    enabled: true
    fields:
      type: api-logs
    fields_under_root: true
    paths:
    - /var/storage/api-logs/*.log
    exclude_files: [".gz"]
    ignore_older: 24h
    encoding: utf-8

  - type: log
    input_type: log
    enabled: true
    fields:
      type: gateway-logs
    fields_under_root: true
    paths:
    - /var/storage/gateway-logs/*.log
    exclude_files: [".gz"]
    ignore_older: 24h
    encoding: utf-8

  - type: log
    input_type: log
    enabled: true
    fields:
      type: api-master-logs
    fields_under_root: true
    paths:
    - /var/storage/api-master-logs/*.log
    exclude_files: [".gz"]
    ignore_older: 24h
    scan_frequency: 60s
    encoding: utf-8

    #  - type: log
#    input_type: log
#    enabled: true
#    fields:
#      type: pipe-logs
#    fields_under_root: true
#    paths:
#    #- /var/storage/pipe-logs/*/*.log
#    #- /var/storage/api-logs/*/anyvision.log
#    #- /var/storage/gateway-logs/*/anyvision.log
#    #- /var/storage/api-master-logs/*/anyvision.log
#    #- /var/storage/*-logs/*/*.log
#    #- /var/storage/*-logs/*.log
#    exclude_files: [".gz"]
#    ignore_older: 24h
#    encoding: utf-8


#    - type: log
#      enabled: true
#      paths:
#         - "/usr/share/filebeat/pipe-logs/pipe_236408ed-a726-41f4-aaf0-f18c354d20fb/*.log"
#           #- "/var/log/*.log"
#
#    - type: log
#      paths:
#          - "/usr/share/filebeat/api-logs/*.log"
#
#    - type: log
#      paths:
#          - "/usr/share/filebeat/gateway-logs/*.log"


# document_type: nginx-access
output:
  logstash:
    hosts: ["logstash"]
    port: 5044


#================================ Logging =====================================

# Sets log level. The default log level is info.
# Available log levels are: error, warning, info, debug
logging.level: info

# At debug level, you can selectively enable logging only for some components.
# To enable all selectors use ["*"]. Examples of other selectors are "beat",
# "publish", "service".
logging.selectors: ["*"]

#from: https://www.elastic.co/guide/en/beats/filebeat/1.2/configuration-filebeat-options.html