version: '3.3'

networks:
  prod:
    external: true


services:

  dockerregistry:
    image: registry:2
    restart: always
    networks:
      prod:
        aliases:
          - dockerregistry.tls.ai
    ports:
     - 5000:5000
    volumes:
      - /storage/dockerregistry:/var/lib/registry
      #- /usr/local/share/ca-certificates/anyvision:/certs
    environment:
      - REGISTRY_HTTP_ADDR=0.0.0.0:5000
      #- REGISTRY_HTTP_TLS_CERTIFICATE=/certs/anyvisionCA.pem
      #- REGISTRY_HTTP_TLS_KEY=/certs/anyvisionCA.key.pem
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    logging:
      options:
        max-size: 1g