version: "2"

services:
  # brocker
  redis:
    image: redis:3.2.6
    container_name: redis
    volumes:
      - redis-data:/data
    networks:
      - logging

  # index, search & agregation
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.4
    container_name: elastic
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - $PWD/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - "es-data:/usr/share/elasticsearch/data"
    networks:
      - logging

  # UI
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.2.4
    container_name: kibana
    ports:
      - 5601:5601
    volumes:
      - $PWD/kibana/config/kibana.yml:/etc/kibana/kibana.yml
    networks:
      - logging
    depends_on:
      - elasticsearch

  # indexer
  logstash:
    image: docker.elastic.co/logstash/logstash-oss:6.2.4
    container_name: logstash
    command: logstash -f /config/
    environment:
      - LS_JAVA_OPTS=-Xms1g -Xmx1g
    volumes:
      - $PWD/logstash/config:/config
    networks:
      - logging
    depends_on:
      - elasticsearch
      - redis

  filebeat:
    image: docker.elastic.co/beats/filebeat:6.2.4
    container_name: filebeat
    volumes:
      - $PWD/filebeat/config/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - /storage/logs:/usr/share/filebeat/logs:ro
    networks:
      - logging
    depends_on:
      - logstash

volumes:
  es-data:
    driver: local
  redis-data:
    driver: local

networks:
  logging:
    driver: bridge
