version: '3.3'

networks:
  monitor-net:
  anyvision:
    external:
      name: docker-compose_anyvision


volumes:
    prometheus_data:
    grafana_data:
    swarm-endpoints:

services:

#  swarm-discover:
#    image: seqvence/prometheus-swarm
#    command: ["-i", "5", "-o", "/swarm-endpoints/swarm-endpoints.json", "-p" , "prometheus_prometheus"]
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock:rw
#      - swarm-endpoints:/swarm-endpoints:rw
#    labels:
#      prometheus.ignore: "true"

  prometheus:
    image: prom/prometheus:v2.3.2
    volumes:
      - ./prometheus/:/etc/prometheus:rw
      - prometheus_data:/prometheus:rw
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=10d'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    restart: always
    ports:
      - 9090:9090
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"
    logging:
      options:
        max-size: 1g

  alertmanager:
    image: prom/alertmanager:v0.15.2
    volumes:
      - ./alertmanager:/etc/alertmanager:rw
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    restart: always
    ports:
      - 9093:9093
    networks:
      - monitor-net
    environment:
      - ADMIN_USER=${ADMIN_USER:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
    labels:
      org.label-schema.group: "monitoring"
    logging:
      options:
        max-size: 1g

  grafana:
    image: grafana/grafana:5.2.2
    volumes:
      #- grafana_data:/var/lib/grafana:rw
      #- ./grafana/datasources:/etc/grafana/datasources:rw
      #- ./grafana/dashboards:/var/lib/grafana/dashboards:rw
      #- ./grafana/files/:/etc/grafana/files:rw
      - grafana_data:/var/lib/grafana:rw
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini:rw
      - ./grafana/provisioning:/etc/grafana/provisioning:rw
      - ./grafana/dashboards:/var/lib/grafana/dashboards:rw
    #entrypoint: /etc/grafana/files/setup.sh
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: always
    ports:
      - 3001:3000
    networks:
      - monitor-net
    depends_on:
      - prometheus
    labels:
      org.label-schema.group: "monitoring"
    logging:
      options:
        max-size: 1g

  blackbox:
    image: prom/blackbox-exporter:v0.12.0
    restart: always
    ports:
      - "9115:9115"
    networks:
      - monitor-net
      - anyvision
    volumes:
      - ./blackbox-exporter:/config
    command:
      - '--config.file=/config/blackbox.yml'
      - '--log.level=debug'
    labels:
      org.label-schema.group: "monitoring"
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '1gb'
    logging:
      options:
        max-size: 1g

