{
 "title": "Application monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "server", "label": "Server", "query": "label_values(instance)" }
  ]
 },
 "panels": [
  {
   "title": "API Status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "probe_success{instance=~\".*api.*\", instance!~\".*apigateway.*\",instance=~\".*$server.*\"}"
    }
   ]
  },
  {
   "title": "API Gateway Status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "probe_success{instance=~\".*apigateway.*\",instance=~\".*$server.*\"}"
    }
   ]
  },
  {
   "title": "Nginx Status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "probe_success{instance=~\".*nginx.*\",instance=~\".*$server.*\"}"
    }
   ]
  },
  {
   "title": "Pipe Status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "probe_success{instance=~\".*proc.*\",instance=~\".*$server.*\"}"
    }
   ]
  }
 ]
}