{
 "title": "Backend",
 "time": { "from": "now-2m", "to": "now" },
 "refresh": "1s",
 "panels": [
  {
   "title": "Processing Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Sec" }
   ],
   "targets": [
    { "expr": "pipeng_processing_time" }
   ]
  },
  {
   "title": "Number Of Detections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Number Of Detections" }
   ],
   "targets": [
    { "expr": "pipeng_number_of_detections" }
   ]
  },
  {
   "title": "GPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Memory [MB]" }
   ],
   "targets": [
    { "expr": "pipeng_gpu_usage" }
   ]
  },
  {
   "title": "FAPS (Accumulated Avg)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 1, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "Faces Per Second" }
   ],
   "targets": [
    { "expr": "pipeng_faps_avg_accumulated" }
   ]
  },
  {
   "title": "FPS (Accumulated Avg)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 13, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "Frame Per Second" }
   ],
   "targets": [
    { "expr": "pipeng_fps_avg_accumulated" }
   ]
  },
  {
   "title": "Batching - Frame Process Time (Avg Accumulated)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "Frame Avg Process Time [ms]" }
   ],
   "targets": [
    {
     "expr": "pipeng_batchmodule_process_avg_accumulated"
    }
   ]
  },
  {
   "title": "Batching - Frame Wait Time (Avg Accumulated)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "Frame Avg Wait Time [ms]" }
   ],
   "targets": [
    {
     "expr": "pipeng_batchmodule_wait_avg_accumulated"
    }
   ]
  },
  {
   "title": "Detection - Frame Process Time (Avg Accumulated)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "Frame Avg Process Time [ms]" }
   ],
   "targets": [
    {
     "expr": "pipeng_detectormodule_process_avg_accumulated"
    }
   ]
  },
  {
   "title": "Detection - Frame Wait Time (Avg Accumulated)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "Frame Avg Wait Time [ms]" }
   ],
   "targets": [
    {
     "expr": "pipeng_detectormodule_wait_avg_accumulated"
    }
   ]
  },
  {
   "title": "Preview - Frame Process Time (Avg Accumulated)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "Frame Avg Process Time [ms]" }
   ],
   "targets": [
    {
     "expr": "pipeng_previewmodule_process_avg_accumulated"
    }
   ]
  },
  {
   "title": "Preview - Frame Wait Time (Avg Accumulated)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "Frame Avg Wait Time [ms]" }
   ],
   "targets": [
    {
     "expr": "pipeng_previewmodule_wait_avg_accumulated"
    }
   ]
  },
  {
   "title": "FExtracion - Frame Process Time (Avg Accumulated)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "Frame Avg Process Time [ms]" }
   ],
   "targets": [
    {
     "expr": "pipeng_fextractormodule_process_avg_accumulated"
    }
   ]
  },
  {
   "title": "FExtracion - Frame Wait Time (Avg Accumulated)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "Frame Avg Wait Time [ms]" }
   ],
   "targets": [
    {
     "expr": "pipeng_fextractormodule_wait_avg_accumulated"
    }
   ]
  },
  {
   "title": "Tracker - Frame Process Time (Avg Accumulated)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short", "label": "Frame Avg Process Time [ms]" }
   ],
   "targets": [
    {
     "expr": "pipeng_trackermodule_process_avg_accumulated"
    }
   ]
  },
  {
   "title": "Tracker - Frame Wait Time (Avg Accumulated)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 32 },
   "yaxes": [
    { "format": "short", "label": "Frame Avg Wait Time [ms]" }
   ],
   "targets": [
    {
     "expr": "pipeng_trackermodule_wait_avg_accumulated"
    }
   ]
  },
  {
   "title": "Pre Processing - Frame Process Time (Avg Accumulated)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short", "label": "Frame Avg Process Time [ms]" }
   ],
   "targets": [
    {
     "expr": "pipeng_preprocessingmodule_process_avg_accumulated"
    }
   ]
  },
  {
   "title": "Pre Processing - Frame Wait Time (Avg Accumulated)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 32 },
   "yaxes": [
    { "format": "short", "label": "Frame Avg Wait Time [ms]" }
   ],
   "targets": [
    {
     "expr": "pipeng_preprocessingmodule_wait_avg_accumulated"
    }
   ]
  },
  {
   "title": "FAPS (Avg Per Interval)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 3, "y": 40 },
   "yaxes": [
    { "format": "short", "label": "Faces Per Second" }
   ],
   "targets": [
    { "expr": "pipeng_faps_avg_per_interval" }
   ]
  },
  {
   "title": "FPS (Avg Per Interval)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short", "label": "Frames Per Second" }
   ],
   "targets": [
    { "expr": "pipeng_fps_avg_per_interval" }
   ]
  },
  {
   "title": "Batching - Frame Process Time (Avg Per Interval)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short", "label": "Frame Avg Processing Time [ms]" }
   ],
   "targets": [
    {
     "expr": "pipeng_batchmodule_process_avg_per_interval"
    }
   ]
  },
  {
   "title": "Batching - Frame Wait Time (Avg Per Interval)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 48 },
   "yaxes": [
    { "format": "short", "label": "Frame Avg Wait Time [ms]" }
   ],
   "targets": [
    {
     "expr": "pipeng_batchmodule_wait_avg_per_interval"
    }
   ]
  },
  {
   "title": "Detection - Frame Process Time (Avg Per Interval)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short", "label": "Frame Avg Processing Time [ms]" }
   ],
   "targets": [
    {
     "expr": "pipeng_detectormodule_process_avg_per_interval"
    }
   ]
  },
  {
   "title": "Detection - Frame Wait Time (Avg Per Interval)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 48 },
   "yaxes": [
    { "format": "short", "label": "Frame Avg Wait Time [ms]" }
   ],
   "targets": [
    {
     "expr": "pipeng_detectormodule_wait_avg_per_interval"
    }
   ]
  },
  {
   "title": "Preview - Frame Process Time (Avg Per Interval)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short", "label": "Frame Avg Processing Time [ms]" }
   ],
   "targets": [
    {
     "expr": "pipeng_previewmodule_process_avg_per_interval"
    }
   ]
  },
  {
   "title": "Preview - Frame Wait Time (Avg Per Interval)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 56 },
   "yaxes": [
    { "format": "short", "label": "Frame Avg Processing Time [ms]" }
   ],
   "targets": [
    {
     "expr": "pipeng_previewmodule_wait_avg_per_interval"
    }
   ]
  },
  {
   "title": "FE - Frame Process Time (Avg Per Interval)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "short", "label": "Frame Avg Wait Time [ms]" }
   ],
   "targets": [
    {
     "expr": "pipeng_fextractormodule_process_avg_per_interval"
    }
   ]
  },
  {
   "title": "FE - Frame Wait Time (Avg Per Interval)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 56 },
   "yaxes": [
    { "format": "short", "label": "Frame Avg Wait Time [ms]" }
   ],
   "targets": [
    {
     "expr": "pipeng_fextractormodule_wait_avg_per_interval"
    }
   ]
  },
  {
   "title": "Tracker - Frame Wait Time (Avg Per Interval)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short", "label": "Frame Avg Processing Time [ms]" }
   ],
   "targets": [
    {
     "expr": "pipeng_trackermodule_process_avg_per_interval"
    }
   ]
  },
  {
   "title": "Traker - Frame Wait Time (Avg Per Interval)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 64 },
   "yaxes": [
    { "format": "short", "label": "Frame Avg Wait Time [ms]" }
   ],
   "targets": [
    {
     "expr": "pipeng_trackermodule_wait_avg_per_interval"
    }
   ]
  },
  {
   "title": "Pre Processing - Frame Process Time (Avg Per Interval)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "short", "label": "Frame Avg Process Time [ms]" }
   ],
   "targets": [
    {
     "expr": "pipeng_preprocessingmodule_process_avg_per_interval"
    }
   ]
  },
  {
   "title": "Pre Processing - Frame Wait Time (Avg Per Interval)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 64 },
   "yaxes": [
    { "format": "short", "label": "Frame Avg Wait Time [ms]" }
   ],
   "targets": [
    {
     "expr": "pipeng_preprocessingmodule_wait_avg_per_interval"
    }
   ]
  }
 ]
}