{
 "title": "pipe dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "pipe_total_cpu_percent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "pipe_total_cpu_percent" },
    {}
   ]
  },
  {
   "title": "pipe_total_cpu_ram",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "pipe_total_cpu_ram" }
   ]
  },
  {
   "title": "pipe_total_gpu_memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "pipe_total_gpu_load" }
   ]
  },
  {
   "title": "pipe_total_gpu_load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "pipe_total_gpu_load" }
   ]
  },
  {
   "title": "pipe_fps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "pipe_fps" }
   ]
  },
  {
   "title": "pipe_faps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "pipe_faps" }
   ]
  },
  {
   "title": "pipe_latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "pipe_latency" }
   ]
  },
  {
   "title": "pipe_local_storing",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "pipe_local_storing" }
   ]
  },
  {
   "title": "pipe_s3_storing",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "pipe_s3_storing" }
   ]
  },
  {
   "title": "pipe_collate_items",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "pipe_collate_items" }
   ]
  },
  {
   "title": "pipe_collate_received",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "pipe_collate_received" }
   ]
  },
  {
   "title": "pipe_collate_processed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "pipe_collate_processed" }
   ]
  },
  {
   "title": "pipe_objectdetection_cpu_ram",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "pipe_objectdetection_cpu_ram" }
   ]
  },
  {
   "title": "pipe_redis_server_cpu_ram",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "pipe_redis_server_cpu_ram" }
   ]
  },
  {
   "title": "pipe_redis_server_cpu_percent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "pipe_redis_server_cpu_percent" }
   ]
  },
  {
   "title": "pipe_featureextraction_cpu_percent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pipe_featureextraction_cpu_percent"
    }
   ]
  },
  {
   "title": "pipe_objectdetection_cpu_percent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pipe_objectdetection_cpu_percent"
    }
   ]
  },
  {
   "title": "pipe_featureextraction_cpu_ram",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "pipe_featureextraction_cpu_ram" }
   ]
  },
  {
   "title": "pipe_video_detections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "pipe_video_detections" }
   ]
  }
 ]
}